### ISSUE TITLE
Election PBFT test failure

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1129]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=7900&view=ms.vss-test-web.build-test-results-tab&runId=41732&resultId=100047&paneView=debug

```
  File "/mnt/build/1/s/tests/infra/ccf.py", line 544, in network
    yield net
  File "/mnt/build/1/s/tests/election.py", line 66, in run
    request_timeout=(30 if args.consensus == "pbft" else 3)
  File "/mnt/build/1/s/tests/infra/ccf.py", line 439, in find_primary
    raise PrimaryNotFound
infra.ccf.PrimaryNotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/build/1/s/tests/election.py", line 121, in <module>
    run(args)
  File "/mnt/build/1/s/tests/election.py", line 113, in run
    "As expected, primary could not be found after election timeout. Test ended successfully."
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/mnt/build/1/s/tests/infra/ccf.py", line 553, in network
    net.stop_all_nodes()
  File "/mnt/build/1/s/tests/infra/ccf.py", line 299, in stop_all_nodes
    raise NodeShutdownError("Fatal error found during node shutdown")
infra.ccf.NodeShutdownError: Fatal error found during node shutdown
```

**Comment by achamayou** [comment]
Fixed by #1136
