### ISSUE TITLE
Governance history test failure

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1192]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8455&view=ms.vss-test-web.build-test-results-tab&runId=43378&resultId=100024&paneView=attachments

```
2020-05-19 06:13:46.868 | DEBUG    | __main__:count_governance_operations:16 - Audit the ledger file for governance operations
2020-05-19 06:13:46.874 | INFO     | infra.remote:stop:453 - [127.39.23.85] closing
2020-05-19 06:13:46.938 | INFO     | infra.remote:stop:453 - [127.77.221.127] closing
2020-05-19 06:13:47.002 | INFO     | infra.ccf:stop_all_nodes:370 - All nodes stopped...
Traceback (most recent call last):
  File "/mnt/build/1/s/tests/governance_history.py", line 121, in <module>
    run(args)
  File "/mnt/build/1/s/tests/governance_history.py", line 70, in run
    ) = count_governance_operations(ledger)
  File "/mnt/build/1/s/tests/governance_history.py", line 24, in count_governance_operations
    tables = tr.get_public_domain().get_tables()
  File "/mnt/build/1/s/tests/infra/ledger.py", line 126, in get_public_domain
    buffer = io.BytesIO(_byte_read_safe(self._file, self._public_domain_size))
  File "/mnt/build/1/s/tests/infra/ledger.py", line 86, in _byte_read_safe
    raise ValueError("Failed to read precise number of bytes: %u" % num_of_bytes)
ValueError: Failed to read precise number of bytes: 2417
```

The most likely explanation for this is that we are reading the file while some incomplete writes are in flight. The test needs to be made more robust to slow writes.

**Comment by olgavrou** [comment]
Seen again here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=8455&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded

**Comment by achamayou** [comment]
@olgavrou it's the same build :)

**Comment by olgavrou** [comment]
sorry, didn't notice, thought it was an older ticket

**Comment by achamayou** [comment]
Hasn't happened recently, it's been 1m+.
