### ISSUE TITLE
ws_scaffold_raft test failure

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1263]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=9031&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded

55: 2020-06-08 06:24:46.873 | INFO     | infra.remote:stop:448 - [127.243.246.33] closing
55: 2020-06-08 06:24:46.937 | INFO     | infra.ccf:stop_all_nodes:384 - All nodes stopped...
55: Traceback (most recent call last):
55:   File "/mnt/build/1/s/tests/ws_scaffold.py", line 63, in <module>
55:     run(args)
55:   File "/mnt/build/1/s/tests/ws_scaffold.py", line 49, in run
55:     test(network, args, notifications_queue)
55:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 19, in wrapper
55:     return func(*args, **kwargs)
55:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 42, in wrapper
55:     return func(network, args, *nargs, **kwargs)
55:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 42, in wrapper
55:     return func(network, args, *nargs, **kwargs)
55:   File "/mnt/build/1/s/tests/ws_scaffold.py", line 30, in test
55:     assert r.result == True, r.result
55: AssertionError: None
38/57 Test #55: ws_scaffold_raft .................***Failed    3.63 sec

**Comment by achamayou** [comment]
We need to wait for the secondary to open before we send RPC/be robust to it not being open yet.

**Comment by achamayou** [comment]
```
2020-06-26 12:13:23.330 | DEBUG    | infra.clients:log_response:166 - 404 @0.0 Session 'app' is not open.

2020-06-26 12:13:23.330 | INFO     | infra.remote:stop:479 - [127.148.83.86] closing
2020-06-26 12:13:23.394 | INFO     | infra.remote:stop:479 - [127.1.63.155] closing
2020-06-26 12:13:23.458 | INFO     | infra.ccf:stop_all_nodes:388 - All nodes stopped...
Traceback (most recent call last):
  File "/mnt/build/2/s/tests/ws_scaffold.py", line 63, in <module>
    run(args)
  File "/mnt/build/2/s/tests/ws_scaffold.py", line 49, in run
    test(network, args, notifications_queue)
  File "/mnt/build/2/s/tests/suite/test_requirements.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/mnt/build/2/s/tests/suite/test_requirements.py", line 42, in wrapper
    return func(network, args, *nargs, **kwargs)
  File "/mnt/build/2/s/tests/suite/test_requirements.py", line 42, in wrapper
    return func(network, args, *nargs, **kwargs)
  File "/mnt/build/2/s/tests/ws_scaffold.py", line 30, in test
    assert r.result == True, r.result
AssertionError: None
```

**Comment by achamayou** [comment]
We wait for the network to be open, which isn't the same as all the nodes knowing the network is open, so some frontends may still be close if we're fast enough, which we sometimes are.

**Comment by achamayou** [comment]
Happened again, even with the open check. The frontend is OPEN, but forwarded commands are still hitting the error:

```
2020-07-15 14:01:46.425 | INFO     | ccf.clients:log_request:166 - [127.136.151.134:44273] POST /app/log/private {'id': 42, 'msg': 'Hello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHe... (node 0 as user0)
2020-07-15 14:01:46.426 | DEBUG    | ccf.clients:log_response:170 - 200 @2.27 True
2020-07-15 14:01:46.427 | INFO     | ccf.clients:log_request:166 - [127.183.42.63:36717] GET /node/network (node 1 as unauthenticated)
2020-07-15 14:01:46.441 | DEBUG    | ccf.clients:log_response:170 - 200 @2.24 OPEN
2020-07-15 14:01:46.441 | INFO     | __main__:test:40 - Write on secondary through forwarding
2020-07-15 14:01:46.441 | INFO     | ccf.clients:log_request:166 - [127.183.42.63:36717] POST /app/log/private {'id': 42, 'msg': 'Hello world'} (node 1 as user0)
2020-07-15 14:01:46.441 | INFO     | ccf.clients:request:413 - Creating WSS connection
2020-07-15 14:01:46.463 | DEBUG    | ccf.clients:log_response:170 - 404 @0.0 Session 'app' is not open.

2020-07-15 14:01:46.463 | INFO     | infra.remote:stop:481 - [127.136.151.134] closing
2020-07-15 14:01:46.527 | INFO     | infra.remote:stop:481 - [127.183.42.63] closing
2020-07-15 14:01:46.591 | INFO     | infra.network:stop_all_nodes:392 - All nodes stopped...
Traceback (most recent call last):
  File "/mnt/build/2/s/tests/ws_scaffold.py", line 77, in <module>
    run(args)
  File "/mnt/build/2/s/tests/ws_scaffold.py", line 63, in run
    test(network, args, notifications_queue)
  File "/mnt/build/2/s/tests/suite/test_requirements.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/mnt/build/2/s/tests/suite/test_requirements.py", line 43, in wrapper
    return func(network, args, *nargs, **kwargs)
  File "/mnt/build/2/s/tests/suite/test_requirements.py", line 43, in wrapper
    return func(network, args, *nargs, **kwargs)
  File "/mnt/build/2/s/tests/ws_scaffold.py", line 44, in test
    assert r.result == True, r.result
AssertionError: None
```

**Comment by achamayou** [comment]
Waiting for the local commit of network state to be OPEN isn't sufficient. The frontend is only open in the global commit hook, so that must be globally committed, and the hook must have executed.

A more reliable scheme is to retry execution instead, PR'ed under #1407
