### ISSUE TITLE
full_test_suite failure in Daily build

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#1383]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=10358&view=ms.vss-test-web.build-test-results-tab&runId=48362&resultId=100032&paneView=attachments

```
2020-07-06 06:29:33.496 | ERROR    | __main__:run:88 - Test recovery.test failed
Traceback (most recent call last):

  File "/mnt/build/1/s/tests/e2e_suite.py", line 163, in <module>
    run(args)
    │   └ Namespace(app_script=None, binary_dir='.', consensus='raft', debug_nodes=[], domain=None, enclave_type='virtual', enforce_req...
    └ <function run at 0x7feec6585950>

> File "/mnt/build/1/s/tests/e2e_suite.py", line 78, in run
    new_network = test(network, args)
                  │    │        └ Namespace(app_script=None, binary_dir='.', consensus='raft', debug_nodes=[], domain=None, enclave_type='virtual', enforce_req...
                  │    └ <infra.ccf.Network object at 0x7feec65a1290>
                  └ <function test at 0x7feea9e6c7a0>

  File "/mnt/build/1/s/tests/suite/test_requirements.py", line 20, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<infra.ccf.Network object at 0x7feec65a1290>, Namespace(app_script=None, binary_dir='.', consensus='raft', debug_nodes=[], d...
           └ <function test at 0x7feea9e6c8c0>

  File "/mnt/build/1/s/tests/suite/test_requirements.py", line 151, in wrapper
    new_network = func(*args, **kwargs)
                  │     │       └ {}
                  │     └ (<infra.ccf.Network object at 0x7feec65a1290>, Namespace(app_script=None, binary_dir='.', consensus='raft', debug_nodes=[], d...
                  └ <function test at 0x7feea9e6c830>

  File "/mnt/build/1/s/tests/recovery.py", line 22, in test
    recovered_network.start_in_recovery(args, ledger)
    │                 │                 │     └ '/mnt/build/1/s/build/workspace/full_test_suite_common/0.ledger'
    │                 │                 └ Namespace(app_script=None, binary_dir='.', consensus='raft', debug_nodes=[], domain=None, enclave_type='virtual', enforce_req...
    │                 └ <function Network.start_in_recovery at 0x7feea9ec4050>
    └ <infra.ccf.Network object at 0x7feebf146d50>

  File "/mnt/build/1/s/tests/infra/ccf.py", line 346, in start_in_recovery
    self.wait_for_all_nodes_to_catch_up(primary)
    │    │                              └ <infra.node.Node object at 0x7feebf18e110>
    │    └ <function Network.wait_for_all_nodes_to_catch_up at 0x7feea9ec4a70>
    └ <infra.ccf.Network object at 0x7feebf146d50>

  File "/mnt/build/1/s/tests/infra/ccf.py", line 595, in wait_for_all_nodes_to_catch_up
    ), f"Only {len(caught_up_nodes)} (out of {len(self.get_joined_nodes())}) nodes have joined the network"

AssertionError: Only 1 (out of 2) nodes have joined the network
2020-07-06 06:29:33.521 | DEBUG    | __main__:run:114 - Test recovery.test took 37.21 secs
```

Looks like it could just be a slow quote attestation. We ought to log attestation time to rule this out with more confidence when it does happen.

**Comment by achamayou** [comment]
Dupe #1451

**Comment by eddyashton** [comment]
Reopening this to explore a new failure on this `full_test_suite` test, which looks like a seed producing a consistently failing permutation:

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=11931&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=63d660c3-6f76-573a-0154-fd0bcb096ded

This tells us the failing seed:

```
42: 2020-08-25 07:14:49.714 | SUCCESS  | __main__:run:44 - Shuffling full suite with seed 1598339689
```

Repros locally with:

```
$ SHUFFLE_SUITE=ON SHUFFLE_SUITE_SEED=1598339689 ctest -VV -R full_test_suite
```

**Comment by achamayou** [comment]
This is too old for investigation.
