### ISSUE TITLE
votinghistory test fails with secp256k1 curve

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#161]
I built with `-DCURVE_CHOICE=secp256k1_bitcoin`, and the votinghistory test fails with the following error:

```
29: Traceback (most recent call last):
29:   File "/home/v-edasht/src/CCF/tests/votinghistory.py", line 134, in <module>
29:     run(args)
29:   File "/home/v-edasht/src/CCF/tests/votinghistory.py", line 124, in run
29:     verify_sig(cert, sig, req)
29:   File "/home/v-edasht/src/CCF/tests/votinghistory.py", line 22, in verify_sig
29:     pub_key.verify(sig, req, hash_alg)
29:   File "/home/v-edasht/env/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ec.py", line 340, in verify
29:     _ecdsa_sig_verify(self._backend, self, signature, data)
29:   File "/home/v-edasht/env/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ec.py", line 89, in _ecdsa_sig_verify
29:     raise InvalidSignature
29: cryptography.exceptions.InvalidSignature
```

Currently, the CI with the default curve and smallbank off (`ACC_1804_SGX_build` job), and with `secp256k1_bitcoin` only running the small_bank tests (`ACC_1804_SGX_perf_build` job). We don't have coverage of all tests with all curves/other options.

**Comment by rschust** [comment]
Resolved on PR #213
