### ISSUE TITLE
sandbox.sh sometimes fails to start with "Failed to read PID from file"

### ISSUE THREAD

**Issue by letmaik** [microsoft/CCF#1785]
This is related to a misdetection of local/remote nodes.

Sample log:
```
Python environment successfully setup
14:52:12.255 | INFO     | __main__:run:40 - Starting 1 CCF nodes...
14:52:12.255 | WARNING  | __main__:run:42 - Virtual mode enabled
14:52:12.255 | INFO     | infra.network:_setup_common_folder:310 - Creating common folder: .workspace_ccf/sandbox_common
14:52:12.255 | INFO     | infra.proc:ccall:12 - rm -rf .workspace_ccf/sandbox_common
14:52:12.257 | INFO     | infra.proc:ccall:12 - mkdir -p .workspace_ccf/sandbox_common
14:52:12.259 | INFO     | infra.proc:ccall:12 - cp /../CCF/tests/sandbox/sandbox_gov.lua .workspace_ccf/sandbox_common
14:52:12.261 | INFO     | infra.proc:ccall:12 - ln -s /../CCF/samples/apps/poll/keygenerator.sh .workspace_ccf/sandbox_common
14:52:12.262 | INFO     | infra.proc:ccall:12 - /../CCF/build/keygenerator.sh --name member0 --curve secp384r1 --gen-enc-key [cwd: .workspace_ccf/sandbox_common]
14:52:12.274 | INFO     | infra.proc:ccall:12 - /../CCF/build/keygenerator.sh --name user0 --curve secp384r1 [cwd: .workspace_ccf/sandbox_common]
14:52:12.282 | INFO     | infra.network:_start_all_nodes:242 - Opening CCF service on ['127.0.0.1:8000']
14:52:12.356 | DEBUG    | infra.remote:_connect:165 - [127.0.0.1] connect
14:52:12.476 | INFO     | infra.remote:_rc:160 - [127.0.0.1] rm -rf .workspace_ccf/sandbox_0
14:52:12.775 | INFO     | infra.remote:_rc:160 - [127.0.0.1] mkdir -p .workspace_ccf/sandbox_0
14:52:12.780 | INFO     | infra.remote:_setup_files:177 - [127.0.0.1] copy .workspace_ccf/sandbox_0/cchost.virtual from /../CCF/build/cchost.virtual
14:52:13.155 | INFO     | infra.remote:_setup_files:177 - [127.0.0.1] copy .workspace_ccf/sandbox_0/libjs_generic.virtual.so from /../CCF/build/libjs_generic.virtual.so
14:52:14.781 | INFO     | infra.remote:_setup_files:189 - [127.0.0.1] copy .workspace_ccf/sandbox_0/member0_cert.pem from .workspace_ccf/sandbox_common/member0_cert.pem
14:52:14.782 | INFO     | infra.remote:_setup_files:189 - [127.0.0.1] copy .workspace_ccf/sandbox_0/member0_enc_pubk.pem from .workspace_ccf/sandbox_common/member0_enc_pubk.pem
14:52:14.784 | INFO     | infra.remote:_setup_files:189 - [127.0.0.1] copy .workspace_ccf/sandbox_0/sandbox_gov.lua from /../CCF/tests/sandbox/sandbox_gov.lua
14:52:14.784 | INFO     | infra.remote:start:291 - [127.0.0.1] cd .workspace_ccf/sandbox_0 && UBSAN_OPTIONS=print_stacktrace=1 OE_LOG_LEVEL=WARNING ./cchost.virtual --enclave-file=./libjs_generic.virtual.so --enclave-type=virtual --node-address=127.0.0.1:0 --node-address-file=0.node_address --rpc-address=127.0.0.1:8000 --rpc-address-file=0.rpc_address --public-rpc-address=127.0.0.1:8000 --ledger-dir=0.ledger --node-cert-file=0.pem --host-log-level=info --raft-election-timeout-ms=100000 --consensus=cft --worker-threads=0 --sig-tx-interval=5000 --sig-ms-interval=1000 --ledger-chunk-bytes=5MB start --network-cert-file=networkcert.pem --gov-script=sandbox_gov.lua --member-info=member0_cert.pem,member0_enc_pubk.pem 1> .workspace_ccf/sandbox_0/out 2> .workspace_ccf/sandbox_0/err 0< /dev/null
14:52:17.779 | ERROR    | infra.network:_start_all_nodes:291 - Failed to start node 0
Traceback (most recent call last):
  File "/../CCF/tests/sandbox/../start_network.py", line 172, in <module>
    run(args)
    │   └ Namespace(app_script=None, binary_dir='/../CCF/build', common_dir=None, consensus='cft', debug_nodes=[], domai...
    └ <function run at 0x7f3df8434310>
  File "/../CCF/tests/sandbox/../start_network.py", line 69, in run
    network.start_and_join(args)
    │       │              └ Namespace(app_script=None, binary_dir='/../CCF/build', common_dir=None, consensus='cft', debug_nodes=[], domai...
    │       └ <function Network.start_and_join at 0x7f3df8433430>
    └ <infra.network.Network object at 0x7f3df843ab20>
  File "/../CCF/tests/infra/network.py", line 360, in start_and_join
    primary = self._start_all_nodes(args)
              │    │                └ Namespace(app_script=None, binary_dir='/../CCF/build', common_dir=None, consensus='cft', debug_nodes=[], domai...
              │    └ <function Network._start_all_nodes at 0x7f3df8433310>
              └ <infra.network.Network object at 0x7f3df843ab20>
> File "/../CCF/tests/infra/network.py", line 253, in _start_all_nodes
    node.start(
    │    └ <function Node.start at 0x7f3de3f2c430>
    └ <infra.node.Node object at 0x7f3df843ac70>
  File "/../CCF/tests/infra/node.py", line 91, in start
    self._start(
    │    └ <function Node._start at 0x7f3de3f2c5e0>
    └ <infra.node.Node object at 0x7f3df843ac70>
  File "/../CCF/tests/infra/node.py", line 204, in _start
    self.remote.start()
    │    │      └ <function CCFRemote.start at 0x7f3de3f27700>
    │    └ <infra.remote.CCFRemote object at 0x7f3df843ad30>
    └ <infra.node.Node object at 0x7f3df843ac70>
  File "/../CCF/tests/infra/remote.py", line 736, in start
    self.remote.start()
    │    │      └ <function SSHRemote.start at 0x7f3de3f254c0>
    │    └ <infra.remote.SSHRemote object at 0x7f3df843ad90>
    └ <infra.remote.CCFRemote object at 0x7f3df843ad30>
  File "/../CCF/tests/infra/remote.py", line 293, in start
    self.pid()
    │    └ <function SSHRemote.pid at 0x7f3de3f25550>
    └ <infra.remote.SSHRemote object at 0x7f3df843ad90>
  File "/../CCF/tests/infra/remote.py", line 307, in pid
    raise TimeoutError("Failed to read PID from file")
TimeoutError: Failed to read PID from file
14:52:17.783 | INFO     | infra.remote:stop:325 - [127.0.0.1] closing
14:52:18.161 | WARNING  | infra.remote:get_logs:277 - Failed to download .workspace_ccf/sandbox_0/err to .workspace_ccf/sandbox_common/127.0.0.1_0_err (host: 127.0.0.1)
14:52:18.162 | WARNING  | infra.remote:get_logs:277 - Failed to download .workspace_ccf/sandbox_0/out to .workspace_ccf/sandbox_common/127.0.0.1_0_out (host: 127.0.0.1)
14:52:18.162 | INFO     | infra.network:stop_all_nodes:467 - All nodes stopped...
```

**Comment by ebo1981-cyber** [comment]
Please help me to run the ccf app...
In the form of operational steps...
Because I can't get it to work...
I would like you to provide me with a visual guide, if any, to run the ccf

**Comment by achamayou** [comment]
@ebo1981-cyber could you please open a discussion under https://github.com/microsoft/CCF/discussions, and list the steps you have tried and the issues you are facing?

https://microsoft.github.io/CCF/main/build_apps/run_app.html should help you get started, but we're always keen to improve the process and the documentation!

**Comment by ebo1981-cyber** [comment]
dear Amaury Chamayou
when running $ /opt/ccf/bin/sandbox.sh [-p libjs_generic]
appear problem as shown in attached image

**Comment by ebo1981-cyber** [comment]
![image](https://user-images.githubusercontent.com/76199903/141809881-beda4ba0-4ca2-4d70-810c-848ed35e6569.png)

**Comment by achamayou** [comment]
@ebo1981-cyber square brackets are a common CLI convention for optional values (eg. https://github.com/cli/cli/blob/trunk/docs/command-line-syntax.md#optional-arguments). Here in this case, they express that you can optionally pass `-p` followed by a package name such as `libjs_generic`, but you do not have not. If you do however, you should not pass the brackets themselves.

**Comment by ebo1981-cyber** [comment]
mr achamayou ..At first, I would like to thank you very much for your cooperation
After reviewing and executing your notes, while executing a file
tutorial.py
 The problem described in the attachments appeared in the implementation. Please help me bypass it, and if there is a good guide that you provide for me to implement this file, please provide it to me because I need it in the implementation
![photo_2021-11-17_10-50-33](https://user-images.githubusercontent.com/76199903/142159327-0e658cfa-d87b-4b19-a11b-f91eb876bdf8.jpg)
![photo_2021-11-17_10-50-34](https://user-images.githubusercontent.com/76199903/142159334-6d05c6e5-ce4d-4c53-bfb2-194cf0c42f56.jpg)

**Comment by achamayou** [comment]
@ebo1981-cyber the ccf client python package currently requires `httpx == 0.19.*` as expressed in `python/requirements.txt`, may I suggest that you install that version instead of `0.21` and try again?

Please do consider using https://github.com/microsoft/CCF/discussions for support questions.
