### ISSUE TITLE
Can't find network_info.txt when running test_install.sh

### ISSUE THREAD

**Issue by saberrey** [microsoft/CCF#1915]
**Environment:**
ubuntu18 
ccf-0.14.3

**Issue:**
Hi, everyone.
I got some problem when I run script test_install.sh, I get log below:
```
ccf-1@accvm:~/CCF/build$ ./test_install.sh /opt/ccf

07:40:28.276 | INFO     | __main__:run:41 - Starting 1 CCF nodes...
07:40:28.276 | INFO     | infra.network:_setup_common_folder:309 - Creating common folder: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common
07:40:28.276 | INFO     | infra.proc:ccall:12 - rm -rf /home/ccf-1/CCF/build/nested/run/workspace/start_network_common
07:40:28.278 | INFO     | infra.proc:ccall:12 - mkdir -p /home/ccf-1/CCF/build/nested/run/workspace/start_network_common
07:40:28.280 | INFO     | infra.proc:ccall:12 - cp /home/ccf-1/CCF/build/nested/run/../../../src/runtime_config/gov.lua /home/ccf-1/CCF/build/nested/run/workspace/start_network_common
07:40:28.281 | INFO     | infra.proc:ccall:12 - ln -s /home/ccf-1/CCF/build/nested/run/keygenerator.sh /home/ccf-1/CCF/build/nested/run/workspace/start_network_common
07:40:28.283 | INFO     | infra.proc:ccall:12 - /opt/ccf/bin/keygenerator.sh --name member0 --curve secp384r1 --gen-enc-key [cwd: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common]
07:40:28.305 | INFO     | infra.proc:ccall:12 - /opt/ccf/bin/keygenerator.sh --name member1 --curve secp384r1 --gen-enc-key [cwd: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common]
07:40:28.351 | INFO     | infra.proc:ccall:12 - /opt/ccf/bin/keygenerator.sh --name member2 --curve secp384r1 --gen-enc-key [cwd: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common]
07:40:28.414 | INFO     | infra.proc:ccall:12 - /opt/ccf/bin/keygenerator.sh --name user0 --curve secp384r1 [cwd: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common]
07:40:28.422 | INFO     | infra.proc:ccall:12 - /opt/ccf/bin/keygenerator.sh --name user1 --curve secp384r1 [cwd: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common]
07:40:28.436 | INFO     | infra.proc:ccall:12 - /opt/ccf/bin/keygenerator.sh --name user2 --curve secp384r1 [cwd: /home/ccf-1/CCF/build/nested/run/workspace/start_network_common]
07:40:28.444 | INFO     | infra.network:_start_all_nodes:241 - Opening CCF service on ['local://127.0.0.1:8000']
07:40:28.445 | INFO     | infra.remote:_rc:424 - [127.0.0.1] rm -rf /home/ccf-1/CCF/build/nested/run/workspace/start_network_0
07:40:28.447 | INFO     | infra.remote:_rc:424 - [127.0.0.1] mkdir -p /home/ccf-1/CCF/build/nested/run/workspace/start_network_0
07:40:28.449 | INFO     | infra.remote:_rc:424 - [127.0.0.1] ln -s /opt/ccf/bin/cchost /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/cchost
07:40:28.451 | INFO     | infra.remote:_rc:424 - [127.0.0.1] ln -s /build/liblogging.enclave.so.signed /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/liblogging.enclave.so.signed
07:40:28.453 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/workspace/start_network_common/member0_cert.pem /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/member0_cert.pem
07:40:28.455 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/workspace/start_network_common/member0_enc_pubk.pem /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/member0_enc_pubk.pem
07:40:28.457 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/workspace/start_network_common/member1_cert.pem /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/member1_cert.pem
07:40:28.459 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/workspace/start_network_common/member1_enc_pubk.pem /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/member1_enc_pubk.pem
07:40:28.461 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/workspace/start_network_common/member2_cert.pem /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/member2_cert.pem
07:40:28.463 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/workspace/start_network_common/member2_enc_pubk.pem /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/member2_enc_pubk.pem
07:40:28.465 | INFO     | infra.remote:_rc:424 - [127.0.0.1] cp /home/ccf-1/CCF/build/nested/run/../../../src/runtime_config/gov.lua /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/gov.lua
07:40:28.467 | INFO     | infra.remote:start:483 - [127.0.0.1] cd /home/ccf-1/CCF/build/nested/run/workspace/start_network_0 && ./cchost --enclave-file=./liblogging.enclave.so.signed --enclave-type=release --node-address=127.0.0.1:0 --node-address-file=0.node_address --rpc-address=127.0.0.1:8000 --rpc-address-file=0.rpc_address --public-rpc-address=127.0.0.1:8000 --ledger-dir=0.ledger --node-cert-file=0.pem --host-log-level=info --raft-election-timeout-ms=100000 --consensus=cft --worker-threads=0 --sig-tx-interval=5000 --sig-ms-interval=1000 --ledger-chunk-bytes=20KB start --network-cert-file=networkcert.pem --gov-script=gov.lua --member-info=member0_cert.pem,member0_enc_pubk.pem --member-info=member1_cert.pem,member1_enc_pubk.pem --member-info=member2_cert.pem,member2_enc_pubk.pem 1> /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/out 2> /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/err (env: {'OE_LOG_LEVEL': 'WARNING'})
```
**The log in  /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/out:**
```
ccf-1@accvm:~/CCF/build$ cat /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/out
2020-11-24T07:40:28.470202Z        100 [info ] ../src/host/main.cpp:461             | --recovery-threshold unset. Defaulting to number of initial consortium members (3).
2020-11-24T07:40:29+0000.098053Z [(H)WARN] tid(0x7f190251b5c0) | In-enclave logging is not supported. To enable, please add 

from "openenclave/edl/logging.edl" import *;

in the edl file.
 [/source/host/sgx/create.c:oe_create_enclave:1091]
2020-11-24T07:40:29.106429Z        100 [info ] ../src/host/node_connections.h:160   | Listening for node-to-node on 127.0.0.1:41621
2020-11-24T07:40:29.106477Z        100 [info ] ../src/host/rpc_connections.h:75     | Listening for RPCs on 127.0.0.1:8000
2020-11-24T07:40:29.106593Z        100 [info ] ../src/host/main.cpp:664             | Creating new node: new network (with 3 initial member(s) and 3 member(s) required for recovery)
2020-11-24T07:40:29+0000.106654Z [(H)ERROR] tid(0x7f190251b5c0) | :OE_BUFFER_TOO_SMALL [/source/host/calls.c:_call_enclave_function_impl:56]
2020-11-24T07:40:29.106963Z        100 [fatal] ../src/ds/stacktrace_utils.h:54      | Handled fatal signal 6
```

**The log in  /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/err:**
```
ccf-1@accvm:~/CCF/build$ cat /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/err
terminating with uncaught exception of type std::logic_error: Failed to call in enclave_create_node: OE_BUFFER_TOO_SMALL
Stack trace (most recent call last):
#11   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#10   Object "./cchost", at 0x40c099, in 
#9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f1900983b96, in __libc_start_main
#8    Object "./cchost", at 0x4166b2, in 
#7    Object "./cchost", at 0x42b3a0, in 
#6    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f190132f830, in __cxa_throw
#5    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f190132f8a5, in 
#4    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f190132cb55, in 
#3    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f1901316f1e, in 
#2    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f190132da4f, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f19009a28b0, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f19009a0f47, in gsignal
Aborted (Signal sent by tkill() 26949 1000)
```

And I see a log below :
```
Traceback (most recent call last):
  File "/opt/ccf/bin/infra/network.py", line 796, in network
    yield net
  File "/opt/ccf//bin/start_network.py", line 67, in run
    network.start_and_join(args)
  File "/opt/ccf/bin/infra/network.py", line 359, in start_and_join
    primary = self._start_all_nodes(args)
  File "/opt/ccf/bin/infra/network.py", line 252, in _start_all_nodes
    node.start(
  File "/opt/ccf/bin/infra/node.py", line 93, in start
    self._start(
  File "/opt/ccf/bin/infra/node.py", line 206, in _start
    self.remote.get_startup_files(self.common_dir)
  File "/opt/ccf/bin/infra/remote.py", line 745, in get_startup_files
    self.remote.get(self.pem, dst_path)
  File "/opt/ccf/bin/infra/remote.py", line 467, in get
    raise ValueError(path)
ValueError: /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/0.pem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ccf//bin/start_network.py", line 169, in <module>
    run(args)
  File "/opt/ccf//bin/start_network.py", line 118, in run
    LOG.info("Stopping all CCF nodes...")
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/ccf/bin/infra/network.py", line 805, in network
    net.stop_all_nodes()
  File "/opt/ccf/bin/infra/network.py", line 464, in stop_all_nodes
    raise NodeShutdownError("Fatal error found during node shutdown")
infra.network.NodeShutdownError: Fatal error found during node shutdown
```
Is this caused by the above problem？

**Comment by achamayou** [comment]
@saberrey thank you for reporting this issue, this isn't something we've come across before. Could you please post the output of `./tests/sgxinfo.sh`?

**Comment by saberrey** [comment]
The output of /opt/ccf/bin/sgxinfo.sh:
```
ccf-1@accvm:~$ cat /opt/ccf/bin/sgxinfo.sh
#!/bin/bash
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache 2.0 License.

set +e

echo "DRIVER INFO:"
modinfo intel_sgx
echo ""
echo ""

echo "DRIVER LOADED:"
lsmod | grep intel_sgx || echo "Not loaded"
echo ""
echo ""

echo "PSW INFO:"
apt list --installed 2>/dev/null | grep libsgx
echo ""
echo ""

echo "DCAP CLIENT INFO:"
apt list --installed 2>/dev/null | grep az-dcap
echo ""
echo ""

echo "SGX INFO:"
/opt/openenclave/bin/oesgx
```
It has the same error on 0.15.1:
```
ccf-1@accvm:~$ /opt/ccf-${CCF_VERSION}/bin/cchost --version
CCF host: ccf-0.15.1

ccf-1@accvm:~/CCF/build$ cat /home/ccf-1/CCF/build/nested/run/workspace/start_network_0/err
terminating with uncaught exception of type std::logic_error: Failed to call in enclave_create_node: OE_BUFFER_TOO_SMALL
Stack trace (most recent call last):
#11   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#10   Object "./cchost", at 0x40c099, in 
#9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fd2a20e7b96, in __libc_start_main
#8    Object "./cchost", at 0x41670a, in 
#7    Object "./cchost", at 0x42b560, in 
#6    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7fd2a2a93830, in __cxa_throw
#5    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7fd2a2a938a5, in 
#4    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7fd2a2a90b55, in 
#3    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7fd2a2a7af1e, in 
#2    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7fd2a2a91a4f, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fd2a21068b0, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fd2a2104f47, in gsignal
Aborted (Signal sent by tkill() 2586 1000)
```

**Comment by achamayou** [comment]
@saberrey sorry, could you run `/opt/ccf/bin/sgxinfo.sh` and report the output of the script?

**Comment by achamayou** [comment]
This isn't particularly helpful, but I've just run the same on my machine multiple times and I can't reproduce the issue.

**Comment by saberrey** [comment]
Oh, my fault. The output of /opt/ccf/bin/sgxinfo.sh:
```
ccf-1@accvm:~/CCF/build$ /opt/ccf/bin/sgxinfo.sh
DRIVER INFO:
filename:       /lib/modules/5.4.0-1031-azure/updates/dkms/intel_sgx.ko
version:        1.36
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX DCAP Driver
srcversion:     55EB9E27B00356DE5CFF0A1
alias:          acpi*:INT0E0C:*
depends:        
retpoline:      Y
name:           intel_sgx
vermagic:       5.4.0-1031-azure SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4


DRIVER LOADED:
intel_sgx              53248  0


PSW INFO:
libsgx-ae-pce/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-ae-qe3/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-ae-qve/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql-dev/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-quote-verify/unknown,now 1.8.100.2-bionic1 amd64 [installed,upgradable to: 1.9.100.3-bionic1]
libsgx-enclave-common/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-enclave-common-dev/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-headers/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-pce-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-qe3-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-urts/unknown,now 2.12.100.3-bionic1 amd64 [installed]


DCAP CLIENT INFO:
az-dcap-client/bionic,now 1.6 amd64 [installed]


SGX INFO:
CPU supports SGX_FLC:Flexible Launch Control
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 56623104
```

**Comment by achamayou** [comment]
@saberrey thank you, I compared and I was using the 1.8 DCAP, but I upgraded and I still don't have any problem. Could you try upgrading the quote verification enclave so that it's sync with everything else:

```
libsgx-dcap-quote-verify/unknown,now 1.8.100.2-bionic1 amd64 [installed,upgradable to: 1.9.100.3-bionic1]
```

I doubt this is causing the problem, but just in case.

For reference this is my sgxinfo output:

```
DRIVER INFO:
filename:       /lib/modules/5.4.0-1031-azure/kernel/ubuntu/sgx/intel_sgx.ko
version:        1.33
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX DCAP Driver
srcversion:     74405348022B30F54219EC1
alias:          acpi*:INT0E0C:*
depends:        
retpoline:      Y
intree:         Y
name:           intel_sgx
vermagic:       5.4.0-1031-azure SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4


DRIVER LOADED:
intel_sgx              32768  0


PSW INFO:
libsgx-ae-pce/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-ae-qe3/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-ae-qve/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql-dev/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-quote-verify/unknown,now 1.9.100.3-bionic1 amd64 [installed,automatic]
libsgx-enclave-common/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-enclave-common-dev/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-headers/unknown,now 2.12.100.3-bionic1 amd64 [installed,automatic]
libsgx-pce-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-qe3-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-urts/unknown,now 2.12.100.3-bionic1 amd64 [installed]


DCAP CLIENT INFO:
az-dcap-client/bionic,now 1.6 amd64 [installed]


SGX INFO:
CPU supports SGX_FLC:Flexible Launch Control
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 174063616
```

**Comment by saberrey** [comment]
@achamayou thank you for your reply. I upgraded libsgx-dcap-quote-verify, and now my sgxinfo output:
```
ccf-1@accvm:~/CCF/build$ /opt/ccf/bin/sgxinfo.sh
DRIVER INFO:
filename:       /lib/modules/5.4.0-1031-azure/updates/dkms/intel_sgx.ko
version:        1.36
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX DCAP Driver
srcversion:     55EB9E27B00356DE5CFF0A1
alias:          acpi*:INT0E0C:*
depends:        
retpoline:      Y
name:           intel_sgx
vermagic:       5.4.0-1031-azure SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4


DRIVER LOADED:
intel_sgx              53248  0


PSW INFO:
libsgx-ae-pce/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-ae-qe3/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-ae-qve/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql-dev/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-quote-verify/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-enclave-common/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-enclave-common-dev/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-headers/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-pce-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-qe3-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-urts/unknown,now 2.12.100.3-bionic1 amd64 [installed]


DCAP CLIENT INFO:
az-dcap-client/bionic,now 1.6 amd64 [installed]


SGX INFO:
CPU supports SGX_FLC:Flexible Launch Control
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 56623104
```
But still don't work, It has the same problem.

**Comment by achamayou** [comment]
Ok, I've upgraded my driver and now have the exact same dependencies, but still cannot reproduce your issue.

```
DRIVER INFO:
filename:       /lib/modules/5.4.0-1031-azure/updates/dkms/intel_sgx.ko
version:        1.36.2
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX DCAP Driver
srcversion:     27300A67E38AEEFA889568B
alias:          acpi*:INT0E0C:*
depends:        
retpoline:      Y
name:           intel_sgx
vermagic:       5.4.0-1031-azure SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4


DRIVER LOADED:
intel_sgx              53248  0


PSW INFO:
libsgx-ae-pce/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-ae-qe3/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-ae-qve/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-ql-dev/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-dcap-quote-verify/unknown,now 1.9.100.3-bionic1 amd64 [installed,automatic]
libsgx-enclave-common/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-enclave-common-dev/unknown,now 2.12.100.3-bionic1 amd64 [installed]
libsgx-headers/unknown,now 2.12.100.3-bionic1 amd64 [installed,automatic]
libsgx-pce-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-qe3-logic/unknown,now 1.9.100.3-bionic1 amd64 [installed]
libsgx-urts/unknown,now 2.12.100.3-bionic1 amd64 [installed]


DCAP CLIENT INFO:
az-dcap-client/bionic,now 1.6 amd64 [installed]


SGX INFO:
CPU supports SGX_FLC:Flexible Launch Control
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 174063616
```

```
$ cat /data/amchamay/CCF/build/nested/run/workspace/start_network_0/out 
2020-11-24T12:07:04.319805Z        100 [info ] ../src/host/main.cpp:475             | Recovery threshold unset. Defaulting to number of initial consortium members with a public encryption key (3).
2020-11-24T12:07:04+0000.892293Z [(H)WARN] tid(0x7f233ba4c5c0) | In-enclave logging is not supported. To enable, please add 

from "openenclave/edl/logging.edl" import *;

in the edl file.
 [/source/host/sgx/create.c:oe_create_enclave:1091]
2020-11-24T12:07:04.900688Z        100 [info ] ../src/host/node_connections.h:160   | Listening for node-to-node on 127.0.0.1:40361
2020-11-24T12:07:04.900736Z        100 [info ] ../src/host/rpc_connections.h:75     | Listening for RPCs on 127.0.0.1:8000
2020-11-24T12:07:04.900855Z        100 [info ] ../src/host/main.cpp:686             | Creating new node: new network (with 3 initial member(s) and 3 member(s) required for recovery)
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
2020-11-24T12:07:04.983606Z        100 [info ] ../src/host/main.cpp:741             | Created new node
2020-11-24T12:07:04.984052Z -0.083 0   [info ] ../src/consensus/aft/raft.h:1854     | Becoming leader 0: 2
2020-11-24T12:07:04.984061Z -0.083 0   [info ] /src/node/rpc/member_frontend.h:1774 | Create node id: 0
2020-11-24T12:07:04.984064Z -0.083 0   [info ] /src/node/rpc/member_frontend.h:1801 | Created service
2020-11-24T12:07:04.984149Z -0.083 0   [info ] ../src/node/node_state.h:1217        | Network TLS connections now accepted
2020-11-24T12:07:04.984154Z -0.083 0   [info ] ../src/enclave/main.cpp:160          | Starting thread: 0
2020-11-24T12:07:04.984157Z -0.083 0   [info ] ../src/enclave/main.cpp:167          | All threads are ready!
2020-11-24T12:07:10.242618Z -0.292 0   [info ] ../src/node/node_state.h:1459        | Network is OPEN, now accepting user transactions
```

I'll think about it some more...

**Comment by achamayou** [comment]
This is a guess, but it looks to me like you may be hitting a failure at some stage when the code tries to get a quote from OpenEnclave.

Could you please:

1. Confirm this is running an ACC VM
2. Check quote attestation is working. The easiest way to do that is to run the attestation samples from the OpenEnclave SDK: https://github.com/openenclave/openenclave/blob/master/samples/BuildSamplesLinux.md

**Comment by achamayou** [comment]
Just to confirm, were the build artifacts under build/ built against the same version you're passing to test_install.sh?

**Comment by saberrey** [comment]
Hi, achamayou. You are right. I forgot to checkout ccf code to the same version after clone.... 
I checkout to the same version and rebuild., and it works! 
Thank you so much! I think this issue can be closed.

**Comment by achamayou** [comment]
@saberrey thanks for the update, sorry about the trouble, this is something we do want to give better errors about (#1307) but we haven't gotten to it yet.
