### ISSUE TITLE
modules_test failure

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2041]
In Daily

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=17040&view=logs&j=ee9484ec-b476-577b-aa0e-d5ddfcbcd149&t=e2c1a4cf-16d0-5038-f9f6-343f9806d38b

```
50: 08:28:15.394 | INFO     | infra.network:stop_all_nodes:491 - All nodes stopped...
50: Traceback (most recent call last):
50:   File "/mnt/build/1/s/tests/js-modules/modules.py", line 386, in <module>
50:     run(args)
50:   File "/mnt/build/1/s/tests/js-modules/modules.py", line 378, in run
50:     network = test_npm_app(network, args)
50:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 20, in wrapper
50:     return func(*args, **kwargs)
50:   File "/mnt/build/1/s/tests/js-modules/modules.py", line 322, in test_npm_app
50:     jwt = infra.crypto.create_jwt({}, jwt_key_priv_pem, jwt_kid)
50:   File "/mnt/build/1/s/tests/infra/crypto.py", line 195, in create_jwt
50:     return jwt.encode(
50: AttributeError: 'str' object has no attribute 'decode'
```

**Comment by achamayou** [comment]
Also occurs in authentication_test
