### ISSUE TITLE
forum_app test failure

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2042]
In https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=17040&view=logs&j=ee9484ec-b476-577b-aa0e-d5ddfcbcd149&t=e2c1a4cf-16d0-5038-f9f6-343f9806d38b

```
66: TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
66:     at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:34:9)
66:     at formattedImport (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/esm-utils.js:6:23)
66:     at Object.exports.requireOrImport (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/esm-utils.js:23:14)
66:     at Object.exports.loadFilesAsync (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/esm-utils.js:33:34)
66:     at Mocha.loadFilesAsync (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/mocha.js:431:19)
66:     at singleRun (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/cli/run-helpers.js:125:15)
66:     at exports.runMocha (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/cli/run-helpers.js:190:10)
66:     at Object.exports.handler (/mnt/build/1/s/samples/apps/forum/node_modules/mocha/lib/cli/run.js:362:11)
66:     at /mnt/build/1/s/samples/apps/forum/node_modules/mocha/node_modules/yargs/lib/command.js:241:49
66:     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:58:5)
66:     at /mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:34535
66:     at /mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:34176
66:     at process.<anonymous> (/mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:34506)
66:     at Function.<anonymous> (/mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:296856)
66:     at Function.<anonymous> (/mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:296555)
66:     at Function.<anonymous> (/mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:284879)
66:     at Object.apply (/mnt/build/1/s/samples/apps/forum/node_modules/esm/esm.js:1:199341)
66:     at internal/main/run_main_module.js:17:47
```

**Comment by jumaffre** [comment]
I've unsuccessfully looked into this. The error seems similar to https://stackoverflow.com/questions/64261239/mocha-tests-with-esm-support-for-native-es6-modules. I can only reproduce this on a CI machine running in the `ccfciteam/ccf-ci:oe0.13.0` CI container.
