### ISSUE TITLE
Break in release job after member id format change

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2296]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=20227&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=fe98d859-2537-5570-75af-de67d4290f3a

```
Traceback (most recent call last):
  File "/opt/ccf-0.18.5-23-g8996d5d1/bin/start_network.py", line 144, in <module>
    run(args)
  File "/opt/ccf-0.18.5-23-g8996d5d1/bin/start_network.py", line 47, in run
    network.start_in_recovery(
  File "/opt/ccf-0.18.5-23-g8996d5d1/bin/infra/network.py", line 444, in start_in_recovery
    self.consortium = infra.consortium.Consortium(
  File "/opt/ccf-0.18.5-23-g8996d5d1/bin/infra/consortium.py", line 75, in __init__
    new_member = infra.member.Member(
  File "/opt/ccf-0.18.5-23-g8996d5d1/bin/infra/member.py", line 84, in __init__
    assert os.path.isfile(
AssertionError
```

**Comment by jumaffre** [comment]
Fixed by #2300
