### ISSUE TITLE
Replication break in CI

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#256]
```
39: 2019-07-17 07:12:58.803 | DEBUG    | infra.jsonrpc:log_response:229 - #0 {'id': 0, 'result': {'leader_host': b'127.246.19.76', 'leader_id': 0, 'leader_port': b'40272'}, 'error': None, 'jsonrpc': b'2.0', 'commit': 12, 'term': 4, 'global_commit': 12}
39: 2019-07-17 07:12:58.935 | INFO     | infra.jsonrpc:log_request:217 - [127.246.19.76:40272] #0 add_node {'host': '127.73.110.121', 'raftport': '49821', 'pubhost': '127.73.110.121', 'tlsport': '49053', 'cert': [45, 45, 45, 45, 45, 66, 69, 71, 73, 78, 32, 67, 69, 82, 84, 73, 70, 73, 67, 65, 84, 69, 45, 45, 45, 45, 45, 10, 7...
39: 2019-07-17 07:12:59.418 | DEBUG    | infra.jsonrpc:log_response:229 - #0 {'id': 0, 'result': None, 'error': {'code': -32005, 'message': '[TX_FAILED_TO_REPLICATE]: Transaction failed to replicate.'}, 'jsonrpc': '2.0', 'commit': None, 'term': None, 'global_commit': None}
39: 2019-07-17 07:12:59.418 | INFO     | infra.remote:stop:392 - [127.246.19.76] closing
39: 2019-07-17 07:12:59.484 | INFO     | infra.remote:stop:392 - [127.75.130.198] closing
39: 2019-07-17 07:12:59.523 | INFO     | infra.remote:stop:392 - [127.238.73.209] closing
39: 2019-07-17 07:12:59.563 | INFO     | infra.remote:stop:392 - [127.44.232.250] closing
39: 2019-07-17 07:12:59.579 | INFO     | infra.ccf:stop_all_nodes:327 - All remotes stopped...
39: Traceback (most recent call last):
39:   File "/mnt/build/1/s/tests/code_update.py", line 171, in <module>
39:     run(args)
39:   File "/mnt/build/1/s/tests/code_update.py", line 121, in run
39:     assert res
39: AssertionError
6/6 Test #39: code_update_test .................***Failed   23.54 sec

83% tests passed, 1 tests failed out of 6

Label Time Summary:
end_to_end    =  70.96 sec*proc (6 tests)
```

Possibly tied to #249, since that affected serialisation/deserialisation logic?

**Comment by eddyashton** [comment]
I wasn't able to repro this with a fresh build, but I did manage to make the test fail by using the artifact produced in the [failing build](https://msr-gryffindor.visualstudio.com/COCO/_build/results?buildId=15858).

I believe the problem is that while adding nodes on the new code ID we elect a new leader, but then use the original `joinNetwork.json` file containing the old leader's `hostname`. This should be a small fix to use `join_network_custom` in more places, perhaps removing the genesis-gen produced `joinNetwork.json` entirely.

Some other odd things I noticed in the logs:
- While a new node catches up with raft messages, it repeatedly thinks it should be removed as it processes configurations that don't contain itself. Luckily this just prints at the moment, but we'll need to handle this properly for #177.
```
[info ] ../src/host/enclave.h:174            | Quote verified
[info ] ../src/node/nodestate.h:398          | Node has now joined the network as node 5: all domains
[info ] ../src/raft/raft.h:1002              | Becoming follower 5: 2
[info ] ../src/raft/raft.h:1185              | Added node 0
[info ] ../src/raft/raft.h:1185              | Added node 1
[info ] ../src/raft/raft.h:1191              | Removed self 5
[info ] ../src/raft/raft.h:654               | Deserialising signature at 4
[info ] ../src/raft/raft.h:1185              | Added node 2
[info ] ../src/raft/raft.h:1191              | Removed self 5
[info ] ../src/raft/raft.h:654               | Deserialising signature at 6
```
- New nodes trigger always trigger elections while they're catching up. They'll generally lose as they're in the wrong term, but if they trigger once they've caught up they can win and cause an unnecessary leader change. I'm not sure why this happens, as they're clearly receiving append entries messages which should be restarting their election timeout.
```
[info ] ../src/raft/raft.h:945               | Becoming candidate 5: 3
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 6
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 4
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 3
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 2
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 1
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 0
[info ] ../src/raft/raft.h:916               | Recv request vote response to 5 from 6: they voted no
[info ] ../src/raft/raft.h:916               | Recv request vote response to 5 from 4: they voted no
[info ] ../src/raft/raft.h:916               | Recv request vote response to 5 from 3: they voted no
[info ] ../src/raft/raft.h:945               | Becoming candidate 5: 4
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 6
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 4
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 3
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 2
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 1
[info ] ../src/raft/raft.h:770               | Send request vote from 5 to 0
[info ] ../src/raft/raft.h:923               | Recv request vote response to 5 from 4: they voted yes
[info ] ../src/raft/raft.h:923               | Recv request vote response to 5 from 6: they voted yes
[info ] ../src/raft/raft.h:923               | Recv request vote response to 5 from 3: they voted yes
[info ] ../src/raft/raft.h:966               | Becoming leader 5: 4
```

**Comment by achamayou** [comment]
Nice!
