### ISSUE TITLE
LTS test fails to read committed ledger

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2717]
```
79: Traceback (most recent call last):
79:   File "/mnt/build/1/s/tests/lts_compatibility.py", line 407, in <module>
79:     latest_lts_version = run_live_compatibility_with_latest(args, repo, env.branch)
79:   File "/mnt/build/1/s/tests/suite/test_requirements.py", line 20, in wrapper
79:     return func(*args, **kwargs)
79:   File "/mnt/build/1/s/tests/lts_compatibility.py", line 226, in run_live_compatibility_with_latest
79:     run_code_upgrade_from(
79:   File "/mnt/build/1/s/tests/lts_compatibility.py", line 209, in run_code_upgrade_from
79:     network.get_latest_ledger_public_state()
79:   File "/mnt/build/1/s/tests/infra/network.py", line 1034, in get_latest_ledger_public_state
79:     return self._get_ledger_public_view_at(
79:   File "/mnt/build/1/s/tests/infra/network.py", line 1018, in _get_ledger_public_view_at
79:     raise TimeoutError(
79: TimeoutError: Could not read transaction at seqno 337 from ledger ['/mnt/build/1/s/build/workspace/lts_compatibility_4/0.ledger.current', '/mnt/build/1/s/build/workspace/lts_compatibility_4/0.ledger.committed']
61/69 Test #79: lts_compatibility .................***Failed   73.32 sec
```

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=27843&view=logs&j=7c757bb7-415c-5163-de32-12a6f7a25c74&t=4191c7c4-7cdc-5cdb-00e9-e20c36964866

**Comment by achamayou** [comment]
We have an implicit assumption that the file is flushed quickly enough, which may or not may not hold.

**Comment by achamayou** [comment]
This is still happening occasionally, presumably when Azure storage IO is very slow.

**Comment by achamayou** [comment]
Not observed recently.
