### ISSUE TITLE
partitions_test failure

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#2768]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=28489&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&s=d654deb9-056d-50a2-1717-90c08683d50a&t=bb1a7e6d-8f5b-56e4-638c-b498b20b4b62&l=351

```
61: Traceback (most recent call last):
61:   File "/mnt/build/2/s/tests/partitions_test.py", line 159, in <module>
61:     run(args)
61:   File "/mnt/build/2/s/tests/partitions_test.py", line 150, in run
61:     test_isolate_and_reconnect_primary(network, args)
61:   File "/mnt/build/2/s/tests/suite/test_requirements.py", line 20, in wrapper
61:     return func(*args, **kwargs)
61:   File "/mnt/build/2/s/tests/partitions_test.py", line 129, in test_isolate_and_reconnect_primary
61:     assert False, f"Stuck at {r}: {pprint.pformat(details)}"
61: AssertionError: Stuck at <green>200</> <yellow>{"transaction_id":"8.23"}</>: {'details': {'acks': {'8646797e88253a40f846d8bf3f14c7353942431f996b5f2fedb93765e5f7cba6': 23,
61:                       '8f9a9aa365f1b137d4779efd499bb4c5b9cf7d7313ae61a4cf51366308e988b8': 23},
61:              'configs': [{'idx': 5,
61:                           'nodes': {'56349f090c3c9b1261436d5b8f8ad9443e85a23d5ee8114017cbc89d29d59b37': {'address': '127.229.16.204:41755'},
61:                                     '8646797e88253a40f846d8bf3f14c7353942431f996b5f2fedb93765e5f7cba6': {'address': '127.9.226.218:44125'},
61:                                     '8f9a9aa365f1b137d4779efd499bb4c5b9cf7d7313ae61a4cf51366308e988b8': {'address': '127.230.161.49:32779'}}}],
61:              'state': 'Follower'}}

```

**Comment by achamayou** [comment]
Not seen recently, presumed fix by recent Raft changes, will re-open if necessary.

**Comment by letmaik** [comment]
Happened again: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=38850&view=logs&j=b69c18ba-eebc-5249-7cb0-46eb355ef417&t=3fb8c875-5663-5738-37c0-e2e2e8559dd0

```
51: Traceback (most recent call last):
51:   File "/__w/1/s/tests/partitions_test.py", line 330, in <module>
51:     run(args)
51:   File "/__w/1/s/tests/partitions_test.py", line 313, in run
51:     test_isolate_and_reconnect_primary(network, args, iteration=n)
51:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
51:     return func(*args, **kwargs)
51:   File "/__w/1/s/tests/partitions_test.py", line 144, in test_isolate_and_reconnect_primary
51:     assert (
51: AssertionError: Stuck before 11.67: {'details': {'acks': {'6ec5053df621ce2a79af1c3f4329920de209559e01508aef67f864ba458e5755': 65,
51:                       'ddf13e8013405d82d45db86c6497a156afbbdcf44866fa19d570fe5404c12b41': 0},
51:              'configs': [{'idx': 57,
51:                           'nodes': {'151d31013905733401dde4d8c091847f6dbd8554c206e231f5ce75e710095c7f': {'address': '127.135.176.27:35287'},
51:                                     '6ec5053df621ce2a79af1c3f4329920de209559e01508aef67f864ba458e5755': {'address': '127.105.177.191:45361'},
51:                                     'ddf13e8013405d82d45db86c6497a156afbbdcf44866fa19d570fe5404c12b41': {'address': '127.189.206.223:41199'}},
51:                           'rid': 0}],
51:              'leadership_state': 'Follower',
51:              'membership_state': 'Active',
51:              'reconfiguration_type': 'OneTransaction'}}
```

**Comment by wintersteiger** [comment]
Third time in three days that I see this fail during PR CI runs:

```
55: Traceback (most recent call last):
55:   File "/__w/1/s/tests/partitions_test.py", line 143, in test_isolate_and_reconnect_primary
55:     c.wait_for_commit(new_tx_resp, timeout=(network.election_duration * 4))
55:   File "/__w/1/s/tests/infra/clients.py", line 728, in wait_for_commit
55:     infra.commit.wait_for_commit(self, response.seqno, response.view, timeout)
55:   File "/__w/1/s/tests/infra/commit.py", line 51, in wait_for_commit
55:     raise TimeoutError(
55: TimeoutError: Timed out waiting for commit: {'details': {'acks': {'97ca324d715744cb6caa73281f6b1fc2b3d053afe08eae7e3d9f57a96b15b19c': 72,
55:                       'a06e909824d08bb25c631dd4fe7d16a126fe72370f1f11d9270e530be37ead27': 0},
55:              'configs': [{'idx': 58,
55:                           'nodes': {'97ca324d715744cb6caa73281f6b1fc2b3d053afe08eae7e3d9f57a96b15b19c': {'address': '127.216.152.193:35805'},
55:                                     'a06e909824d08bb25c631dd4fe7d16a126fe72370f1f11d9270e530be37ead27': {'address': '127.243.153.6:41267'},
55:                                     'b1e4f602e2a22215b0e571332914517b5e169de9307bfa21933d64f35ccface1': {'address': '127.143.250.157:35933'}},
55:                           'rid': 58}],
55:              'leadership_state': 'Candidate',
55:              'membership_state': 'Active',
55:              'reconfiguration_type': 'OneTransaction'}}
55: 
55: During handling of the above exception, another exception occurred:
55: 
55: Traceback (most recent call last):
55:   File "/__w/1/s/tests/partitions_test.py", line 351, in <module>
55:     run(args)
55:   File "/__w/1/s/tests/partitions_test.py", line 334, in run
55:     test_isolate_and_reconnect_primary(network, args, iteration=n)
55:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
55:     return func(*args, **kwargs)
55:   File "/__w/1/s/tests/partitions_test.py", line 146, in test_isolate_and_reconnect_primary
55:     assert (
55: AssertionError: Stuck before 14.74: {'details': {'acks': {'97ca324d715744cb6caa73281f6b1fc2b3d053afe08eae7e3d9f57a96b15b19c': 72,
55:                       'a06e909824d08bb25c631dd4fe7d16a126fe72370f1f11d9270e530be37ead27': 0},
55:              'configs': [{'idx': 58,
55:                           'nodes': {'97ca324d715744cb6caa73281f6b1fc2b3d053afe08eae7e3d9f57a96b15b19c': {'address': '127.216.152.193:35805'},
55:                                     'a06e909824d08bb25c631dd4fe7d16a126fe72370f1f11d9270e530be37ead27': {'address': '127.243.153.6:41267'},
55:                                     'b1e4f602e2a22215b0e571332914517b5e169de9307bfa21933d64f35ccface1': {'address': '127.143.250.157:35933'}},
55:                           'rid': 58}],
55:              'leadership_state': 'Candidate',
55:              'membership_state': 'Active',
55:              'reconfiguration_type': 'OneTransaction'}}
1/1 Test #55: partitions_cft ...................***Failed   75.47 sec

```

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=42846&view=logs&j=8f3dc89c-3708-5926-47e7-27120a268dab&t=7bd34434-39f0-5895-0268-9c8695195ee2&l=595

**Comment by achamayou** [comment]
Not been observed in a long time.
