### ISSUE TITLE
Failure "RPC could not be forwarded to unknown primary" in Daily CI

### ISSUE THREAD

**Issue by rengolin** [microsoft/CCF#3367]
**Describe the bug**
[Here](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=39586&view=logs&j=383d248c-4494-5797-d98f-6cef5140601e&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=ae32e15b-0191-5f39-7410-be7e80165871&l=15160): `"error":{"code":"InternalError","message":"RPC could not be forwarded to unknown primary."`

Stack Trace:
```
48: Traceback (most recent call last):
48:   File "/__w/1/s/tests/js-modules/modules.py", line 615, in <module>
48:     run(args)
48:     │   └ Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_ledger_dir=None, config_file=None, consensus='CFT', co...
48:     └ <function run at 0x7fb52f785940>
48:   File "/__w/1/s/tests/js-modules/modules.py", line 608, in run
48:     network = test_npm_app(network, args)
48:     │         │            │        └ Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_ledger_dir=None, config_file=None, consensus='CFT', co...
48:     │         │            └ <infra.network.Network object at 0x7fb52f1015b0>
48:     │         └ <function test_npm_app at 0x7fb52ef874c0>
48:     └ <infra.network.Network object at 0x7fb52f1015b0>
48:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
48:     return func(*args, **kwargs)
48:            │     │       └ {}
48:            │     └ (<infra.network.Network object at 0x7fb52f1015b0>, Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_led...
48:            └ <function test_npm_app at 0x7fb52ef87430>
48:   File "/__w/1/s/tests/js-modules/modules.py", line 584, in test_npm_app
48:     assert r.status_code == http.HTTPStatus.UNAUTHORIZED, r.status_code
48:            │                │                             └ Response(status_code=503, body=b'{"error":{"code":"InternalError","message":"RPC could not be forwarded to unknown primary."}}',...
48:            │                └ <module 'http' from '/usr/lib/python3.8/http/__init__.py'>
48:            └ Response(status_code=503, body=b'{"error":{"code":"InternalError","message":"RPC could not be forwarded to unknown primary."}}',...
48: AssertionError: 503
```

The test seems to be swapping leader/folower and it seems to work, here's a grep of the logs:
```
modules_v8_test_0.out:2022-01-09T08:25:39.863701Z        0   [info ] ../src/consensus/aft/raft.h:1828     | Becoming leader n[0e430ae6e27d7556c577dae5c5826b6bc13e4e7a28b8a0a2f4a1790177ba5c23]: 2
modules_v8_test_1.out:2022-01-09T08:25:41.640621Z -0.005 0   [info ] ../src/consensus/aft/raft.h:1890     | Becoming follower n[c3cac8fcca17741ae9542915c547204e4206d9a212f8c4232afc161d5d2157a8]: 0.0
modules_v8_test_1.out:2022-01-09T08:25:41.660376Z -0.002 0   [info ] ../src/consensus/aft/raft.h:1890     | Becoming follower n[c3cac8fcca17741ae9542915c547204e4206d9a212f8c4232afc161d5d2157a8]: 2.0
...
modules_v8_test_1.out:2022-01-09T08:27:15.586285Z -0.001 0   [info ] ../src/consensus/aft/raft.h:1783     | Becoming candidate n[c3cac8fcca17741ae9542915c547204e4206d9a212f8c4232afc161d5d2157a8]: 3
modules_v8_test_1.out:2022-01-09T08:27:16.083142Z -0.002 0   [info ] ../src/consensus/aft/raft.h:1828     | Becoming leader n[c3cac8fcca17741ae9542915c547204e4206d9a212f8c4232afc161d5d2157a8]: 3
modules_v8_test_0.out:2022-01-09T08:27:16.081201Z -0.008 0   [info ] ../src/consensus/aft/raft.h:1890     | Becoming follower n[0e430ae6e27d7556c577dae5c5826b6bc13e4e7a28b8a0a2f4a1790177ba5c23]: 3.83
```

The only fails are in node 0:
```
modules_v8_test_0.out:2022-01-09T08:25:47.222903Z -0.005 0   [fail ] /endpoints/endpoint_registry.cpp:332 | Found multiple potential templated matches for request path
modules_v8_test_0.out:2022-01-09T08:25:47.223056Z -0.005 0   [fail ] ../src/http/http_endpoint.h:216      | Closing connection
modules_v8_test_0.out:2022-01-09T08:25:47.223150Z -0.005 0   [fail ] ../src/http/http_endpoint.h:77       | Error parsing HTTP request
modules_v8_test_0.out:2022-01-09T08:26:00.378118Z        100 [fail ] ../src/host/time_bound_logger.h:55   | Operation took too long (187.674ms): Reading framed ledger entries from 58 to 58
modules_v8_test_0.out:2022-01-09T08:26:02.263734Z        100 [fail ] ../src/host/time_bound_logger.h:55   | Operation took too long (190.497ms): Reading framed ledger entries from 60 to 60
modules_v8_test_0.out:2022-01-09T08:26:06.215213Z        100 [fail ] ../src/host/time_bound_logger.h:55   | Operation took too long (369.414ms): Reading framed ledger entries from 62 to 62
```

Which doesn't seem related to V8?

**Comment by rengolin** [comment]
Note: I reran the test and it passed, so this is probably not a V8 bug but an instability issue.

**Comment by letmaik** [comment]
The failing job is the Instrumented one which uses the V8 debug build. Maybe it got so slow that it was on the edge of triggering some CCF / infra timeouts?

**Comment by achamayou** [comment]
Not been observed in a long time.
