### ISSUE TITLE
Failure "PrimaryNotFound" in Daily CI

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3368]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=39586&view=logs&j=62a51552-835c-5bc7-8b94-1c4e1e3fa3fa&t=e9f61859-18a9-578f-c07c-850acd97df57

```
54: 2022-01-09 10:52:51.917 | ERROR    | {js_v8} infra.runner:log_exception:217 - Failure in js_v8: TestRequirementsNotMet('Could not check if test requirements were met: ')
54: Traceback (most recent call last):
54: 
54:   File "/__w/1/s/tests/suite/test_requirements.py", line 34, in wrapper
54:     check_reqs(network, args, *nargs, **kwargs)
54:     │          │        │      │        └ {}
54:     │          │        │      └ ()
54:     │          │        └ Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_ledger_dir=None, config_file=None, consensus='CFT', co...
54:     │          └ <infra.network.Network object at 0x7f0cc596f5b0>
54:     └ <function supports_methods.<locals>.check at 0x7f0cc595f1f0>
54:   File "/__w/1/s/tests/suite/test_requirements.py", line 62, in check
54:     primary, _ = network.find_primary()
54:                  └ <infra.network.Network object at 0x7f0cc596f5b0>
54:   File "/__w/1/s/tests/infra/network.py", line 763, in find_primary
54:     raise PrimaryNotFound
54:           └ <class 'infra.network.PrimaryNotFound'>
54: 
54: infra.network.PrimaryNotFound
54: 
54: 
54: The above exception was the direct cause of the following exception:
54: 
54: 
54: Traceback (most recent call last):
54: 
54:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
54:     self.run()
54:     └ <Thread(js_v8, started 139692820305664)>
54:   File "/usr/lib/python3.8/threading.py", line 870, in run
54:     self._target(*self._args, **self._kwargs)
54:     │             │             └ <Thread(js_v8, started 139692820305664)>
54:     │             └ <Thread(js_v8, started 139692820305664)>

```

**Comment by rengolin** [comment]
I haven't seen this error message before:
```
54: Traceback (most recent call last):
54:   File "/__w/1/s/tests/e2e_logging.py", line 1308, in <module>
54:     cr.run()
54:     └ <infra.runner.ConcurrentRunner object at 0x7f0cc59668e0>
54:   File "/__w/1/s/tests/infra/runner.py", line 297, in run
54:     raise Exception(FAILURES)
54:                     └ ["Failure in js_v8: TestRequirementsNotMet('Could not check if test requirements were met: ')"]
54: Exception: ["Failure in js_v8: TestRequirementsNotMet('Could not check if test requirements were met: ')"]
45/55 Test #54: e2e_logging_cft ..................***Failed  128.26 sec
```

Is that the primary not being found? Could it be the same instability that triggered #3367?

**Comment by rengolin** [comment]
Another example:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=43557&view=logs&j=ee9484ec-b476-577b-aa0e-d5ddfcbcd149&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=571d2419-8d7e-5f32-5a70-005e0b0ec140&l=210

The log shows:
```
55: 14:15:48.476 | ERROR    | infra.remote:log_errors:77 - /__w/1/s/build/workspace/partitions_cft_0/out: 2022-03-23T14:15:48.387587Z        100 [fail ] ../src/host/tcp.h:708                | on_connect: cancelled
55: 14:15:48.477 | INFO     | infra.remote:log_errors:80 - 1 errors found, printing end of output for context:
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.363938Z -0.001 0   [trace] ../src/node/channels.h:222           | <- n[3dc72eaad06b6371248f1a2a077ca2362faa080eaa386da6ad43d9f816228ed2] (ESTABLISHED): decrypt(25 bytes, 0 bytes) (nonce=317)
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.363970Z -0.001 0   [debug] ../src/consensus/aft/raft.h:1563     | Recv append entries response to n[39baf4f1590552c6beecf242beafde37fbb9c172616c68841ed3fd17355b29ca] from n[3dc72eaad06b6371248f1a2a077ca2362faa080eaa386da6ad43d9f816228ed2] for index 24: success
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.363993Z -0.001 0   [debug] ../src/consensus/aft/raft.h:2011     | In update_commit, new_commit_cft_idx: 24, last_idx: 24
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.364014Z -0.001 0   [debug] ../src/consensus/aft/raft.h:2033     | Commit if possible 24 (ci: 24) (ti 7)
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.386193Z        100 [info ] ../src/host/sig_term.h:24            | SIGTERM: Shutting down enclave gracefully...
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.387338Z -0.001 0   [info ] ../src/enclave/enclave.h:466         | Enclave stopped successfully. Stopping host...
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.387384Z        100 [info ] ../src/host/handle_ring_buffer.h:99  | Host stopped successfully
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.387405Z        100 [info ] ../src/host/main.cpp:572             | Exited event loop
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.387587Z        100 [fail ] ../src/host/tcp.h:708                | on_connect: cancelled
55: 14:15:48.477 | INFO     | infra.remote:log_errors:84 - 2022-03-23T14:15:48.387619Z        100 [info ] ../src/host/main.cpp:590             | Ran an extra 1 cleanup iteration(s)
```

And the python stack:
```
55: Traceback (most recent call last):
55:   File "/__w/1/s/tests/partitions_test.py", line 372, in <module>
55:     run(args)
55:   File "/__w/1/s/tests/partitions_test.py", line 352, in run
55:     test_isolate_primary_from_one_backup(network, args)
55:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
55:     return func(*args, **kwargs)
55:   File "/__w/1/s/tests/suite/test_requirements.py", line 48, in wrapper
55:     return func(network, args, *nargs, **kwargs)
55:   File "/__w/1/s/tests/partitions_test.py", line 119, in test_isolate_primary_from_one_backup
55:     new_primary, new_view = network.wait_for_new_primary(
55:   File "/__w/1/s/tests/infra/network.py", line 1066, in wait_for_new_primary
55:     raise error(f"A new primary was not elected after {timeout} seconds")
55: infra.network.PrimaryNotFound: A new primary was not elected after 30.0 seconds
```

Other than the `on_connect: cancelled` that stands out, every thing else seems fine?

**Comment by achamayou** [comment]
Not been observed in a long time.
