### ISSUE TITLE
Connection error in CI (recovery_test_suite)

### ISSUE THREAD

**Issue by rengolin** [microsoft/CCF#3377]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=39674&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=cf4e34b3-24ee-5d97-0df9-ba9302d9fe90&l=6301

```
42: 12:14:52.628 | INFO     | infra.node:_start:310 - Node 7 started: 802c048af98f5d9a511c75f8de837184afc4b6ecd0cdcb19ef340e252f7f31a6
42: 12:14:55.676 | WARNING  | infra.network:find_primary:753 - Could not successfully connect to node 3. Retrying...
42: 12:14:55.689 | INFO     | infra.network:find_primary:765 - [4||] GET /node/network
42: 12:14:55.689 | INFO     | infra.network:find_primary:765 - 200 @4.147 {"current_view":4,"primary_id":"8b5620d2ff639f391082cc29b7743a809e9cfca1f27b613d428eff0a9a26dbc1","service_certificate":"-----BEGIN CERTIFICATE-----\nMIIBejCCASGgAwIBAgIRAK4Tv5JLvLVAc3NqyMmN5VkwCgYIKoZIzj0EAwIwFjEU\nMBIGA1UEAwwLQ0NGIE5ldHdvcmswHhcNMjEwMzEx + 475 chars
42: 12:14:58.709 | INFO     | infra.consortium:_check_node_exists:580 - [3||] GET /node/network/nodes/802c048af98f5d9a511c75f8de837184afc4b6ecd0cdcb19ef340e252f7f31a6
42: 12:14:58.709 | ERROR    | __main__:run:128 - Test reconfiguration.test_add_node failed
42: Traceback (most recent call last):
42: 
42:   File "/__w/1/s/build/env/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
42:     yield
42:   File "/__w/1/s/build/env/lib/python3.8/site-packages/httpcore/backends/sync.py", line 82, in connect_tcp
42:     sock = socket.create_connection(
42:            │      └ <function create_connection at 0x7f4724ae3f70>
42:            └ <module 'socket' from '/usr/lib/python3.8/socket.py'>
42:   File "/usr/lib/python3.8/socket.py", line 808, in create_connection
42:     raise err
42:           └ None
42:   File "/usr/lib/python3.8/socket.py", line 796, in create_connection
42:     sock.connect(sa)
42:     │    │       └ ('127.253.53.142', 43215)
42:     │    └ <method 'connect' of '_socket.socket' objects>
42:     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
42: 
42: ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by wintersteiger** [comment]
That build has been deleted, so we can't see the node logs (they're in the build artefacts) nor can we see which part of the build this happened in. It's possible that this is another instance of  #3491 and the node error log contained a UBSAN or ASAN complaint.
