### ISSUE TITLE
LTS compatibility check fails for Unsafe build

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3653]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=43144&view=logs&j=abb827b0-1387-5f0d-393d-8da14bd7f99d&t=328e9e87-12fb-5696-903c-0f14a0ce494d

```
59: 03:29:44.070 | INFO     | infra.jwt_issuer:stop:92 - OpenIdProviderServer stopped
59: Traceback (most recent call last):
59:   File "/__w/1/s/tests/lts_compatibility.py", line 587, in <module>
59:     lts_versions = run_ledger_compatibility_since_first(
59:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
59:     return func(*args, **kwargs)
59:            │     │       └ {'use_snapshot': False}
59:            │     └ (Namespace(binary_dir='/__w/1/s/build', ccf_version='ccf-2.0.0-rc4_unsafe', check_2tx_reconfig_migration=True, check_ledger_comp...
59:            └ <function run_ledger_compatibility_since_first at 0x7f631d21ad30>
59:   File "/__w/1/s/tests/lts_compatibility.py", line 449, in run_ledger_compatibility_since_first
59:     network.recover(args)
59:     │               └ Namespace(binary_dir='/__w/1/s/build', ccf_version='ccf-2.0.0-rc4_unsafe', check_2tx_reconfig_migration=True, check_ledger_compa...
59:     └ <infra.network.Network object at 0x7f631c8798e0>
59:   File "/__w/1/s/tests/infra/network.py", line 533, in recover
59:     if random_node.version_after("ccf-2.0.0-rc3")
59:   File "/__w/1/s/tests/infra/node.py", line 637, in version_after
59:     self_rc, self_num_rc_tkns = version_rc(self.version)
59:                                 │          └ <infra.node.Node object at 0x7f631c886610>
59:                                 └ <function version_rc at 0x7f631d90d8b0>
59:   File "/__w/1/s/tests/infra/node.py", line 89, in version_rc
59:     return (int(rc_tkn[2:]), len(tokens)) if rc_tkn else (None, 0)
59:                 │                │           └ 'rc4_unsafe'
59:                 │                └ ['ccf', '2.0.0', 'rc4_unsafe']
59:                 └ 'rc4_unsafe'
59: ValueError: invalid literal for int() with base 10: '4_unsafe'
50/53 Test #59: lts_compatibility ................***Failed  295.81 sec
```

**Comment by achamayou** [comment]
Two possibilities:

1. Because Unsafe is Release with extra logging, we decide that re-running the tests is a waste of time and execution resources, not to mention time spent fixing these naming issues
2. We add special logic to the LTS test to drop _unsafe suffixes where present

I think I favour 1. but want to hear what everyone thinks first.

**Comment by eddyashton** [comment]
I favour 1. While we'd _like_ `_unsafe` builds to be able to start from an old ledger, and co-exist with other nodes, and...

We're not going to _guarantee_ that. If there are really any cases where the `_unsafe` build is LTs non-compatible, in a way that the `Release` build isn't, I don't think they're worth our time to fix!

So let's just drop this test.

**Comment by achamayou** [comment]
Ok, we'll skip the LTS test when `UNSAFE_VERSION` is on.
