### ISSUE TITLE
Reconfiguration test break

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#3808]
CI: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=44959&view=logs&j=e982d093-d12a-5a2d-1a1d-0c6d38b8823f&t=8be5454d-0d8f-51e4-7372-58df022e9ebc

```
62: 2022-05-04 03:41:35.688 | ERROR    | {1tx_reconfig} infra.runner:log_exception:211 - Failure in 1tx_reconfig: ValueError('Response seqno and view should not be None')
62: Traceback (most recent call last):
62: 
62:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
62:     self.run()
62:     └ <Thread(1tx_reconfig, started 140040401565440)>
62:   File "/usr/lib/python3.8/threading.py", line 870, in run
62:     self._target(*self._args, **self._kwargs)
62:     │             │             └ <Thread(1tx_reconfig, started 140040401565440)>
62:     │             └ <Thread(1tx_reconfig, started 140040401565440)>
62:     └ <Thread(1tx_reconfig, started 140040401565440)>
62:   File "/__w/1/s/tests/reconfiguration.py", line 571, in run
62:     test_retire_primary(network, args)
62:     │                   │        └ Namespace(binary_dir='/__w/1/s/build', ccf_version='ccf-2.0.0-rc8-1-ge3f677a2', common_read_only_ledger_dir=None, config_file=No...
62:     │                   └ <infra.network.Network object at 0x7f5da9936820>
62:     └ <function test_retire_primary at 0x7f5da9bfb160>
62:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
62:     return func(*args, **kwargs)
62:            │     │       └ {}
62:            │     └ (<infra.network.Network object at 0x7f5da9936820>, Namespace(binary_dir='/__w/1/s/build', ccf_version='ccf-2.0.0-rc8-1-ge3f677a2...
62:            └ <function test_retire_primary at 0x7f5da9bfb280>
62:   File "/__w/1/s/tests/suite/test_requirements.py", line 48, in wrapper
62:     return func(network, args, *nargs, **kwargs)
62:            │    │        │      │        └ {}
62:            │    │        │      └ ()
62:            │    │        └ Namespace(binary_dir='/__w/1/s/build', ccf_version='ccf-2.0.0-rc8-1-ge3f677a2', common_read_only_ledger_dir=None, config_file=No...
62:            │    └ <infra.network.Network object at 0x7f5da9936820>
62:            └ <function test_retire_primary at 0x7f5da9bfb1f0>
62:   File "/__w/1/s/tests/reconfiguration.py", line 291, in test_retire_primary
62:     check_can_progress(backup)
62:     │                  └ <infra.node.Node object at 0x7f5da9936d60>
62:     └ <function check_can_progress at 0x7f5da9f3a280>
62:   File "/__w/1/s/tests/infra/checker.py", line 53, in check_can_progress
62:     c.wait_for_commit(r, timeout=timeout)
62:     │                 │          └ 3
62:     │                 └ Response(status_code=503, body=b'{"error":{"code":"InternalError","message":"RPC could not be forwarded to unknown primary."}}',...
62:     └ <infra.clients.CCFClient object at 0x7f5da98b17c0>
62:   File "/__w/1/s/tests/infra/clients.py", line 726, in wait_for_commit
62:     raise ValueError("Response seqno and view should not be None")
62: 
62: ValueError: Response seqno and view should not be None
```

**Comment by jumaffre** [comment]
The issue seems to be due to backup `2` no longer knowing the primary [by the time we check the service can make progress](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=44959&view=logs&j=e982d093-d12a-5a2d-1a1d-0c6d38b8823f&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=8be5454d-0d8f-51e4-7372-58df022e9ebc&l=52644):
```
62: 2022-05-04 03:41:34.928 | INFO     | {1tx_reconfig} infra.network:wait_for_new_primary:1081 - [2||] GET /node/network
62: 2022-05-04 03:41:34.928 | INFO     | {1tx_reconfig} infra.network:wait_for_new_primary:1081 - 200 @3.167 {"current_view":4,"primary_id":"8b026f31e12ca7fe65542797270ccad65b9166c741bbd901f5783f56c3f55f94","service_certificate":"-----BEGIN CERTIFICATE-----\nMIIBtzCCAT2gAwIBAgIQGTF1dbk2WjT0WFvzJt4djDAKBggqhkjOPQQDAzAWMRQw\nEgYDVQQDDAtDQ0YgTmV0d29yazAeFw0yMjA1MDQw + 559 chars
62: 2022-05-04 03:41:34.928 | INFO     | {1tx_reconfig} infra.network:wait_for_new_primary:1083 - New primary after 2.28s is 5 (8b026f31e12ca7fe65542797270ccad65b9166c741bbd901f5783f56c3f55f94) in term 4

...

62: 2022-05-04 03:41:34.970 | INFO     | {1tx_reconfig} infra.checker:_post_private_record:44 - [2|user0|] POST /app/log/private?scope=check_can_progress {'id': 3, 'msg': 'Hello world'}
62: 2022-05-04 03:41:34.970 | INFO     | {1tx_reconfig} infra.checker:_post_private_record:44 - 503 {"error":{"code":"InternalError","message":"RPC could not be forwarded to unknown primary."}}
```

The logs for node `2` don't seem to indicate anything suspicious:
```
2022-05-04T03:41:34.899510Z -0.002 0   [info ] ../src/consensus/aft/raft.h:1874     | Becoming follower n[d66192ba03b815a3a96e32b41ec0a8382e485478c542008aa6fcbd207aaf1c7e]: 4.165

* Primary is known here *

2022-05-04T03:41:34.952278Z -0.005 0   [info ] ../src/node/channels.h:802           | Node channel with n[938c0e065014010547808cb1e1092f5680d2be29e6cddb13a3cd185f1fcae7ce] is now established.
2022-05-04T03:41:34.952300Z -0.001 0   [info ] ../src/consensus/aft/raft.h:1668     | Send request vote response from n[d66192ba03b815a3a96e32b41ec0a8382e485478c542008aa6fcbd207aaf1c7e] to n[938c0e065014010547808cb1e1092f5680d2be29e6cddb13a3cd185f1fcae7ce]: true

* Primary is unknown here *

2022-05-04T03:41:34.986512Z -0.006 0   [info ] ../src/consensus/aft/raft.h:2459     | Removed raft node n[faf00dd115b97abf80dc69883ca6b256c5c5dc23baab96bf57be5416fa63f71a]
2022-05-04T03:41:35.099583Z        100 [info ] ../src/host/sig_term.h:24            | SIGTERM: Shutting down enclave gracefully...
```
