### ISSUE TITLE
SSL peer shut down incorrectly with CCF commit version `7939befcae7acaef23a499e6fea20b00b625cca3'

### ISSUE THREAD

**Issue by chantong-ubs** [microsoft/CCF#414]
The error was from Java client side (MADRec application) to establish the connection with CCF server. Once we had this error from CCF server, the CCF server was not usable and needs to restart.

[Error Exception Stack]
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1322)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1160)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:716)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:970)
        at java.base/java.io.OutputStream.write(OutputStream.java:122)
        at com.ubs.madrec.ccbf.rpc.TlsClient.call(TlsClient.java:111)
        at com.ubs.madrec.ccbf.rpc.TlsClient.call(TlsClient.java:127)
        at com.ubs.madrec.ccbf.rpc.TlsClient.call(TlsClient.java:127)
        at com.ubs.madrec.ccbf.rpc.TlsClient.call(TlsClient.java:127)
        at com.ubs.madrec.ccbf.rpc.TlsClient.call(TlsClient.java:135)
        at com.ubs.madrec.ccbf.rpc.RpcTlsClient.call(RpcTlsClient.java:43)
        at com.ubs.madrec.ccbf.rpc.RpcTlsClient.callR(RpcTlsClient.java:65)
        at com.ubs.madrec.ccbf.clients.MemberImpl.addClient(MemberImpl.java:38)
        at com.ubs.madrec.ccbf.clients.MemberImpl.addUser(MemberImpl.java:50)
        at com.ubs.madrec.coco.ServiceContainer.init(ServiceContainer.java:33)
        at com.ubs.madrec.coco.controller.CredentialsRestController.getCertificate(CredentialsRestController.java:130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        ... 70 more

**Comment by achamayou** [comment]
@chantong-ubs thank you for reporting this issue, would you be able to provide the node log, or the most recent lines?

Does this happen first thing after starting the node, or after a specific sequence of transactions?

**Comment by chantong-ubs** [comment]
The error happened after the CCF node running for a while (could be hours or days). I believed only for new user to establish new socket connection with the CCF node. I was not pay attention the CCF node log. I will need to reproduce the problem to search for node log.
    On Friday, October 4, 2019, 02:45:20 PM EDT, Amaury Chamayou <notifications@github.com> wrote:  
 
 
@chantong-ubs thank you for reporting this issue, would you be able to provide the node log, or the most recent lines?

Does this happen first thing after starting the node, or after a specific sequence of transactions?

**Comment by chantong-ubs** [comment]
Attached node 0 log file
    On Friday, October 4, 2019, 03:17:15 PM EDT, Chan Tong <chantong00@yahoo.com> wrote:  
 
  The error happened after the CCF node running for a while (could be hours or days). I believed only for new user to establish new socket connection with the CCF node. I was not pay attention the CCF node log. I will need to reproduce the problem to search for node log.
    On Friday, October 4, 2019, 02:45:20 PM EDT, Amaury Chamayou <notifications@github.com> wrote:  
 
 
@chantong-ubs thank you for reporting this issue, would you be able to provide the node log, or the most recent lines?

Does this happen first thing after starting the node, or after a specific sequence of transactions?

**Comment by achamayou** [comment]
@chantong-ubs email attachments do not make it to github, can you please find another way to provide the log?

This sounds like a duplicate of https://github.com/microsoft/CCF/issues/264, please confirm that the file descriptors for the process are not exhausted when trying to connect. To get open file descriptors: ls -la /proc/$PID/fd

To get the max number of file descriptors per process, see "Max open files" under /proc/$PID/limits

**Comment by chantong-ubs** [comment]
[0.log](https://github.com/microsoft/CCF/files/3702441/0.log)
Node 0 log file

**Comment by achamayou** [comment]
@chantong-ubs that's an (encrypted) ledger, I meant the log of the node you were trying to connect to.
