### ISSUE TITLE
Unstable partitions test

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#4165]
The partitions test has recently become unstable in the CI.

Sample failure:

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=48870&view=logs&j=383d248c-4494-5797-d98f-6cef5140601e&t=db780f4b-6bb4-5a89-1068-06386e3ab5e7&l=1246

```
63: Traceback (most recent call last):
63:   File "/__w/1/s/tests/partitions_test.py", line 502, in <module>
63:     run(args)
63:   File "/__w/1/s/tests/partitions_test.py", line 485, in run
63:     test_election_reconfiguration(network, args)
63:   File "/__w/1/s/tests/suite/test_requirements.py", line 20, in wrapper
63:     return func(*args, **kwargs)
63:   File "/__w/1/s/tests/suite/test_requirements.py", line 48, in wrapper
63:     return func(network, args, *nargs, **kwargs)
63:   File "/__w/1/s/tests/partitions_test.py", line 345, in test_election_reconfiguration
63:     assert False, "No new primary should be elected while partition is up"
63: AssertionError: No new primary should be elected while partition is up
1/1 Test #63: partitions_cft ...................***Failed  130.10 sec
```

**Comment by eddyashton** [comment]
Sketching my understanding:

- We have 3 nodes `[0, 1, 2]`, primary is 0
- We start (join but _don't trust_) 3 more nodes `[3, 4, 5]`
- We partition the original backups `[1, 2]`
- We trust the new nodes, wait for _them_ to hear this, then kill the original primary
- We're trying to confirm that `[3, 4, 5]` can't make progress without the original quorum

I think there's 2 bugs here:
- `[1, 2]` are partitioned from `0`, but _not_ from `[3, 4, 5]`, so they _will_ vote for those new nodes, if those new nodes are up-to-date fast enough
  - ```
        # Also partition from nodes that are not explicitly passed in in a partition
        other_nodes = [
            node for node in self.network.get_joined_nodes() if node not in nodes
        ]
    ```
- The only thing that prevents the original backups `[1, 2]`  voting for those new nodes in some runs is that they have elected a new primary amongst themselves, and produced a signature. Essentially they made independent progress on another fork, so won't vote for the new nodes.

I think the fix is to both build a stronger partition, that includes partitioning the old backups from the new nodes, and also partitioning the backups from each other to prevent a single majority partition simply making progress on its fork (and passing the test in an unexpected way).
