### ISSUE TITLE
Recovery test attempts unsafe reads, and does not handle incomplete files

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#4459]
```
Traceback (most recent call last):
  File "/opt/ccf_sgx_unsafe/bin/start_network.py", line 215, in <module>
    run(args)
  File "/opt/ccf_sgx_unsafe/bin/start_network.py", line 80, in run
    network.start_in_recovery(
  File "/opt/ccf_sgx_unsafe/bin/infra/network.py", line 550, in start_in_recovery
    public_state, _ = ledger.get_latest_public_state()
  File "/__w/2/s/python/ccf/ledger.py", line 1022, in get_latest_public_state
    for chunk in self:
  File "/__w/2/s/python/ccf/ledger.py", line 881, in __next__
    self._current_chunk = LedgerChunk(
  File "/__w/2/s/python/ccf/ledger.py", line 844, in __init__
    self._current_tx = Transaction(name, ledger_validator)
  File "/__w/2/s/python/ccf/ledger.py", line 697, in __init__
    _byte_read_safe(self._file, LEDGER_HEADER_SIZE), byteorder="little"
  File "/__w/2/s/python/ccf/ledger.py", line 327, in _byte_read_safe
    raise ValueError(
ValueError: Failed to read precise number of bytes in 0.ledger/ledger_20215 at offset 0: 0/8
Waiting for service to open...
Sandbox process has terminated
Error: Timeout waiting 600s for service to open
```

**Comment by achamayou** [comment]
Another instance in https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=53497&view=logs&j=abb827b0-1387-5f0d-393d-8da14bd7f99d&t=82b6ffee-2988-5a53-54fa-b0f27fe21589

**Comment by eddyashton** [comment]
Another instance in `SGX Unsafe`, in the `Daily` job here: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=53634&view=logs&j=abb827b0-1387-5f0d-393d-8da14bd7f99d&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=82b6ffee-2988-5a53-54fa-b0f27fe21589&l=207

```
Waiting for service to open...
Waiting for service to open...
Waiting for service to open...
Traceback (most recent call last):
  File "/opt/ccf_sgx_unsafe/bin/start_network.py", line 215, in <module>
    run(args)
  File "/opt/ccf_sgx_unsafe/bin/start_network.py", line 80, in run
    network.start_in_recovery(
  File "/opt/ccf_sgx_unsafe/bin/infra/network.py", line 550, in start_in_recovery
    public_state, _ = ledger.get_latest_public_state()
  File "/__w/1/s/python/ccf/ledger.py", line 1022, in get_latest_public_state
    for chunk in self:
  File "/__w/1/s/python/ccf/ledger.py", line 881, in __next__
    self._current_chunk = LedgerChunk(
  File "/__w/1/s/python/ccf/ledger.py", line 844, in __init__
    self._current_tx = Transaction(name, ledger_validator)
  File "/__w/1/s/python/ccf/ledger.py", line 697, in __init__
    _byte_read_safe(self._file, LEDGER_HEADER_SIZE), byteorder="little"
  File "/__w/1/s/python/ccf/ledger.py", line 327, in _byte_read_safe
    raise ValueError(
ValueError: Failed to read precise number of bytes in 0.ledger/ledger_20143 at offset 0: 0/8
Waiting for service to open...
Sandbox process has terminated
Error: Timeout waiting 600s for service to open
./recovery_benchmark.sh: line 126: kill: (17778) - No such process
./recovery_benchmark.sh: line 76: kill: (17778) - No such process
```
