### ISSUE TITLE
SIGSEGV, Segmentation fault in src/consensus/aft/test/logging_stub.h

### ISSUE THREAD

**Issue by lemmy** [microsoft/CCF#4681]
Initially reported in https://github.com/microsoft/CCF/issues/4582 

https://github.com/microsoft/CCF/blob/1e2708f7c504ca4eb91d9dfaf756c5793e369702/src/consensus/aft/test/logging_stub.h#L304

```c
root@codespaces-0aefa5:/workspaces/CCF/tests/raft_scenarios# gdb ../../build/raft_driver             
GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../../build/raft_driver...
(gdb) r 4582
Starting program: /workspaces/CCF/build/raft_driver 4582
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
<RaftDriver>  n[0]->>n[0]: periodic for 500 ms
<RaftDriver>  n[0]->>n[0]: [KV] initialising in term 1
<RaftDriver>  Note right of n[0]: P @1.0 (committed 0)
<RaftDriver>  Note over n[1]: Node n[1] created
<RaftDriver>  n[0]->>n[0]: periodic for 500 ms
<RaftDriver>  n[1]->>n[1]: periodic for 500 ms
<RaftDriver>  n[1]->>n[1]: [KV] initialising in term 1
<RaftDriver>  Note right of n[0]: P @1.0 (committed 0)
<RaftDriver>  Note right of n[1]: P @1.0 (committed 0)
<RaftDriver>  n[0]->>n[0]: replicate 1.1 = [0 bytes]  [reconfiguration]

Program received signal SIGSEGV, Segmentation fault.
0x00000000004349cc in std::__1::__tree_is_left_child<std::__1::__tree_node_base<void*>*> (__x=0x1623041) at /usr/lib/llvm-10/bin/../include/c++/v1/__tree:81
81          return __x == __x->__parent_->__left_;
(gdb) backtrace
#0  0x00000000004349cc in std::__1::__tree_is_left_child<std::__1::__tree_node_base<void*>*> (__x=0x1623041) at /usr/lib/llvm-10/bin/../include/c++/v1/__tree:81
#1  std::__1::__tree_next_iter<std::__1::__tree_end_node<std::__1::__tree_node_base<void*>*>*, std::__1::__tree_node_base<void*>*> (__x=0x1623041) at /usr/lib/llvm-10/bin/../include/c++/v1/__tree:184
#2  std::__1::__tree_iterator<std::__1::__value_type<ccf::EntityId<ccf::NodeIdFormatter>, kv::Configuration::NodeInfo>, std::__1::__tree_node<std::__1::__value_type<ccf::EntityId<ccf::NodeIdFormatter>, kv::Configuration::NodeInfo>, void*>*, long>::operator++ (this=<optimized out>) at /usr/lib/llvm-10/bin/../include/c++/v1/__tree:848
#3  std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<ccf::EntityId<ccf::NodeIdFormatter>, kv::Configuration::NodeInfo>, std::__1::__tree_node<std::__1::__value_type<ccf::EntityId<ccf::NodeIdFormatter>, kv::Configuration::NodeInfo>, void*>*, long> >::operator++ (this=<optimized out>) at /usr/lib/llvm-10/bin/../include/c++/v1/map:802
#4  aft::ConfigurationChangeHook::call (this=0x1622b20, consensus=0x16221c8) at ../src/consensus/aft/test/logging_stub.h:299
#5  0x000000000043838c in aft::Aft<LedgerStubProxy_Mermaid>::replicate (this=0x16221c8, entries=..., term=<optimized out>) at ../src/consensus/aft/raft.h:785
#6  0x000000000045b928 in RaftDriver::_replicate (this=0x161fad8, term_s=..., data=..., configuration=...) at ../src/consensus/aft/test/driver.h:168
#7  0x000000000040dc65 in RaftDriver::replicate_new_configuration (this=0x161fad8, term_s=..., node_ids=...) at ../src/consensus/aft/test/driver.h:246
#8  0x0000000000407508 in main (argc=<optimized out>, argv=<optimized out>) at ../src/consensus/aft/test/driver.cpp:166
```

**Comment by lemmy** [comment]
Closed with PR #4682
