### ISSUE TITLE
Piccolo's generator cli needs updating to new generator library interface

### ISSUE THREAD

**Issue by heidihoward** [microsoft/CCF#4869]
Piccolo's generator cli  [generate_packages.py](https://github.com/microsoft/CCF/blob/main/tests/perf-system/generator/generate_packages.py) does not appear to work atm. I think it fell out of sync with [generator.py](https://github.com/microsoft/CCF/blob/main/tests/perf-system/generator/generator.py) during refactoring.

Low priority as the library interface works fine.

```
~/CCF/tests/perf-system/generator$ python3.11 generate_packages.py
Traceback (most recent call last):
  File "/home/heidi/CCF/tests/perf-system/generator/generate_packages.py", line 89, in <module>
    main()
  File "/home/heidi/CCF/tests/perf-system/generator/generate_packages.py", line 76, in main
    msg.append(
  File "/home/heidi/CCF/tests/perf-system/generator/generator.py", line 33, in append
    headers.update({k.lower(): v for k, v in additional_headers.items()})
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'items'
```

**Comment by heidihoward** [comment]
I prefer to use generator.py directly as its more expressive. I think its ok to remove.
