### ISSUE TITLE
ASAN: Alloc dealloc mismatch

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5198]
When running tests under ASAN with clang-15, eg https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=69051&view=logs&jobId=fff884fa-70f7-5142-c642-c9647ff4218c&j=fff884fa-70f7-5142-c642-c9647ff4218c&t=002ec585-ff09-575c-f94f-67274e66fb5c

```
2: ==1648==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x606000000380
2: error: did not detect a valid list table with base = 0x0
2: warning: parsing line table prologue at 0x00000455 should have ended at 0x00000869 but it ended at 0x00000868
2:     #0 0x55d63e877d22 in free (/__w/1/s/build/json_schema+0x267d22) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #1 0x7f208923f1fc in std::invalid_argument::~invalid_argument() (/lib/x86_64-linux-gnu/libc++abi.so.1+0x251fc) (BuildId: 965eeee1f4d3fa3085472bfd5d635001bdd965cd)
2:     #2 0x55d63ea17451 in JsonParseError::~JsonParseError() (/__w/1/s/build/json_schema+0x407451) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #3 0x7f2089241551 in __cxa_end_catch (/lib/x86_64-linux-gnu/libc++abi.so.1+0x27551) (BuildId: 965eeee1f4d3fa3085472bfd5d635001bdd965cd)
2:     #4 0x55d63e8eb251 in DOCTEST_ANON_FUNC_14() (/__w/1/s/build/json_schema+0x2db251) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #5 0x55d63e8e4ed7 in doctest::Context::run() (/__w/1/s/build/json_schema+0x2d4ed7) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #6 0x55d63e8ea6a2 in main (/__w/1/s/build/json_schema+0x2da6a2) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #7 0x7f2088b19082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
2:     #8 0x55d63e7f340d in _start (/__w/1/s/build/json_schema+0x1e340d) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2: 
2: 0x606000000380 is located 0 bytes inside of 53-byte region [0x606000000380,0x6060000003b5)
2: allocated by thread T0 here:
2:     #0 0x55d63e8b21ad in operator new(unsigned long) (/__w/1/s/build/json_schema+0x2a21ad) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #1 0x7f208929fd9d in std::logic_error::logic_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (/lib/x86_64-linux-gnu/libc++.so.1+0x4ed9d) (BuildId: e3dee72a81fed73680e4d05b6858c5327d95f499)
2:     #2 0x55d63ea17390 in JsonParseError::JsonParseError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (/__w/1/s/build/json_schema+0x407390) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #3 0x55d63ea160cb in from_json_required_fields(nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, Bar&) (/__w/1/s/build/json_schema+0x4060cb) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #4 0x55d63ea15d74 in from_json(nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, Bar&) (/__w/1/s/build/json_schema+0x405d74) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #5 0x55d63ea15cda in decltype(from_json(fp, std::forward<Bar&>(fp0))) nlohmann::json_abi_v3_11_2::detail::from_json_fn::operator()<nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >, Bar&>(nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, Bar&) const (/__w/1/s/build/json_schema+0x405cda) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #6 0x55d63ea15c1b in decltype((nlohmann::json_abi_v3_11_2::from_json(std::forward<nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&>(fp), fp0)) , ((void)())) nlohmann::json_abi_v3_11_2::adl_serializer<Bar, void>::from_json<nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, Bar>(nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > > const&, Bar&) (/__w/1/s/build/json_schema+0x405c1b) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #7 0x55d63ea15a88 in Bar nlohmann::json_abi_v3_11_2::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long, unsigned long, double, std::__1::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > >::get_impl<Bar, 0>(nlohmann::json_abi_v3_11_2::detail::priority_tag<0u>) const (/__w/1/s/build/json_schema+0x405a88) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #8 0x55d63ea094eb in _ZNK8nlohmann16json_abi_v3_11_210basic_jsonINSt3__13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEE3getI3BarSG_EEDTcldtclL_ZNS2_7declvalIRKSE_EEDTcl9__declvalIT_ELi0EEEvEE8get_implIT0_EtlNS0_6detail12priority_tagILj4EEEEEEv (/__w/1/s/build/json_schema+0x3f94eb) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #9 0x55d63e8eb0fd in DOCTEST_ANON_FUNC_14() (/__w/1/s/build/json_schema+0x2db0fd) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #10 0x55d63e8e4ed7 in doctest::Context::run() (/__w/1/s/build/json_schema+0x2d4ed7) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #11 0x55d63e8ea6a2 in main (/__w/1/s/build/json_schema+0x2da6a2) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5)
2:     #12 0x7f2088b19082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
2: 
2: SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/__w/1/s/build/json_schema+0x267d22) (BuildId: a066697c2e9751b025b08e47983dcba1442054b5) in free
2: ==1648==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
```

**Comment by eddyashton** [comment]
Looks like this is an issue with libcxx (allowing ASAN to insert itself into allocation but not symmetrically in deallocation), and a fix is finally on-the-way:

https://github.com/llvm/llvm-project/issues/59432#issuecomment-1988788696

**Comment by achamayou** [comment]
Closed by #6783
