### ISSUE TITLE
CI failure in limits test on ASAN

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5837]
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=78820&view=logs&j=f0d3fcdb-063b-5a91-fc94-e0704e04da97&t=fb7de1d5-2328-50f0-22e8-af7c9f347ed6

```
54: 2023-11-16 14:58:39.678 | ERROR    | {limits} infra.runner:log_exception:205 - Failure in limits: AssertionError()
54: Traceback (most recent call last):
54: 
54:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
54:     self.run()
54:     └ <Thread(limits, started 140334997870336)>
54:   File "/usr/lib/python3.8/threading.py", line 870, in run
54:     self._target(*self._args, **self._kwargs)
54:     │             │             └ <Thread(limits, started 140334997870336)>
54:     │             └ <Thread(limits, started 140334997870336)>
54:     └ <Thread(limits, started 140334997870336)>
54:   File "/__w/1/s/tests/js-custom-authorization/custom_authorization.py", line 239, in run_limits
54:     network = test_execution_time_limit(network, args)
54:     │         │                         │        └ Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_ledger_dir=None, config_file=None, consensus='CFT', co...
54:     │         │                         └ <infra.network.Network object at 0x7fa26058d9d0>
54:     │         └ <function test_execution_time_limit at 0x7fa26057c8b0>
54:     └ <infra.network.Network object at 0x7fa26058d9d0>
54:   File "/__w/1/s/tests/suite/test_requirements.py", line 21, in wrapper
54:     return func(*args, **kwargs)
54:            │     │       └ {}
54:            │     └ (<infra.network.Network object at 0x7fa26058d9d0>, Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_led...
54:            └ <function test_execution_time_limit at 0x7fa26057c820>
54:   File "/__w/1/s/tests/js-custom-authorization/custom_authorization.py", line 225, in test_execution_time_limit
54:     assert r.status_code == http.HTTPStatus.INTERNAL_SERVER_ERROR
54:            │                └ <module 'http' from '/usr/lib/python3.8/http/__init__.py'>
54:            └ Response(status_code=200, body=b'', seqno=271, view=2, headers=Headers({'content-length': '0', 'x-ms-ccf-transaction-id': '2.271...
54: 
54: AssertionError: assert r.status_code == http.HTTPStatus.INTERNAL_SERVER_ERROR
```

Failure in the execution time cap test on the ASAN build. No stderr/SAN output, the request went through despite the cap being 0, which is surprising and needs investigation.

**Comment by achamayou** [comment]
Another occurrence: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=79421&view=logs&j=f0d3fcdb-063b-5a91-fc94-e0704e04da97&t=fb7de1d5-2328-50f0-22e8-af7c9f347ed6

**Comment by achamayou** [comment]
No recent reproduction, will re-open if needed.
