### ISSUE TITLE
Daily build failure in `modules_test`: Expired certificate in "Test verifySnpAttestation with a static attestation report"

### ISSUE THREAD

**Issue by eddyashton** [microsoft/CCF#5884]
Failing from this morning.

Example failing instance here:
https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=79856&view=logs&j=f0d3fcdb-063b-5a91-fc94-e0704e04da97&t=fb7de1d5-2328-50f0-22e8-af7c9f347ed6&l=34813

Example output:
```
53: 03:51:57.174 | INFO     | __main__:test_npm_app:1175 - Virtual: Test verifySnpAttestation with a static attestation report
53: 03:51:57.368 | INFO     | __main__:test_npm_app:1200 - [0|tls=user0] POST /app/verifySnpAttestation {'evidence': 'AgAAAAIAAAAfAAMAAAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAADAAAAAAAI0gEAAAAAAAAAAAAAAAAAAAALt5ll0S8wqAkXMEGAo4huW4CWlKdF+ZJri26zboUxJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/6gKCMYmyXQYjpcgfl8i6TS+8SMkUpVzlJfkEVN3OwwN0Pawv + 24514 chars
53: 03:51:57.368 | INFO     | __main__:test_npm_app:1200 - 400 {"error":{"message":"certificate chain verification failed: certificate has expired (depth: 0)"}}
53: 03:51:57.368 | INFO     | infra.network:network:1711 - Stopping network
53: 03:51:57.368 | INFO     | infra.node:stop:469 - Stopping node 0
53: 03:51:57.368 | INFO     | infra.remote:stop:515 - [127.172.148.70] closing
53: 03:51:58.635 | ERROR    | infra.network:log_errors:126 - /__w/1/s/build/workspace/modules_test_0/out:201: 2024-01-04T03:50:59.409827Z -0.007 0   [fail ] /endpoints/endpoint_registry.cpp:547 | Found multiple potential templated matches for request path
53: 03:51:58.636 | ERROR    | infra.network:log_errors:126 - /__w/1/s/build/workspace/modules_test_0/out:202: 2024-01-04T03:50:59.409991Z -0.007 0   [fail ] ../src/http/http_session.h:263       | Closing connection
53: 03:51:58.636 | INFO     | infra.network:log_errors:129 - 2 errors found, printing end of output for context:
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:56.944004Z -0.030 0   [info ][js] _generic/js_generic_base.cpp:604 | JS execution complete: Method=POST, Path=/app/isValidX509CertChain, Status=200, ExecMilliseconds=25
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.036322Z -0.030 0   [info ][js] _generic/js_generic_base.cpp:604 | JS execution complete: Method=POST, Path=/app/isValidX509CertChain, Status=200, ExecMilliseconds=27
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.071680Z -0.032 0   [info ][js] _generic/js_generic_base.cpp:604 | JS execution complete: Method=POST, Path=/app/isValidX509CertChain, Status=200, ExecMilliseconds=26
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.164361Z -0.030 0   [info ][js] _generic/js_generic_base.cpp:604 | JS execution complete: Method=POST, Path=/app/isValidX509CertChain, Status=200, ExecMilliseconds=27
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.366023Z -0.130 0   [info ][js] _generic/js_generic_base.cpp:604 | JS execution complete: Method=POST, Path=/app/verifySnpAttestation, Status=400, ExecMilliseconds=109
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.370004Z        100 [info ] ../src/host/sig_term.h:39            | Terminated: Shutting down enclave gracefully...
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.371214Z -0.003 0   [info ] ../src/enclave/enclave.h:493         | Enclave stopped successfully. Stopping host...
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.371332Z        100 [info ] ../src/host/handle_ring_buffer.h:100 | Host stopped successfully
53: 03:51:58.636 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.371445Z        100 [info ] ../src/host/main.cpp:792             | Exited event loop
53: 03:51:58.637 | INFO     | infra.network:log_errors:133 - 2024-01-04T03:51:57.371843Z        100 [info ] ../src/host/main.cpp:810             | Ran an extra 1 cleanup iteration(s)
53: 03:51:58.637 | INFO     | infra.node:stop:469 - Stopping node 1
53: 03:51:58.637 | INFO     | infra.remote:stop:515 - [127.119.31.87] closing
53: 03:51:59.703 | INFO     | infra.network:stop_all_nodes:858 - All nodes stopped
53: Traceback (most recent call last):
53:   File "/__w/1/s/tests/js-modules/modules.py", line 1450, in <module>
53:     run(args)
53:     │   └ Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_ledger_dir=None, config_file=None, consensus='CFT', co...
53:     └ <function run at 0x7f87122161f0>
53:   File "/__w/1/s/tests/js-modules/modules.py", line 1441, in run
53:     network = test_npm_app(network, args)
53:     │         │            │        └ Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_ledger_dir=None, config_file=None, consensus='CFT', co...
53:     │         │            └ <infra.network.Network object at 0x7f8712222730>
53:     │         └ <function test_npm_app at 0x7f8712216310>
53:     └ <infra.network.Network object at 0x7f8712222730>
53:   File "/__w/1/s/tests/suite/test_requirements.py", line 21, in wrapper
53:     return func(*args, **kwargs)
53:            │     │       └ {}
53:            │     └ (<infra.network.Network object at 0x7f8712222730>, Namespace(binary_dir='/__w/1/s/build', ccf_version=None, common_read_only_led...
53:            └ <function test_npm_app at 0x7f8712216280>
53:   File "/__w/1/s/tests/js-modules/modules.py", line 1208, in test_npm_app
53:     assert r.status_code == http.HTTPStatus.OK, r.status_code
53:            │                │                   └ Response(status_code=400, body=b'{"error":{"message":"certificate chain verification failed: certificate has expired (depth: 0)"...
53:            │                └ <module 'http' from '/usr/lib/python3.8/http/__init__.py'>
53:            └ Response(status_code=400, body=b'{"error":{"message":"certificate chain verification failed: certificate has expired (depth: 0)"...
53: AssertionError: 400
43/61 Test #53: modules_test .....................***Failed   73.52 sec
```

Test was added in #5690, includes a hard-coded SNP attestation. We could fetch a fresh attestation from a more recent run, but we don't want to regularly refresh test data to handle expiring certs.

**Comment by eddyashton** [comment]
Spent a while tracking down where the certificate validation fails (we generally ignore time checks in CCF), and it turns out its during `didx509` resolution while processing the `uvm_endorsements`. In `verify_uvm_endorsements`, we call `didx509::resolve` in the 3rdparty `didx509cpp` library. Luckily this already has a flag to ignore time checks as we do elsewhere. Fix is in #5885.
