### ISSUE TITLE
Python dependencies install fails during CI

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#6546]
Sample: https://github.com/microsoft/CCF/actions/runs/11239974653/job/31248339552

```
× Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Traceback (most recent call last):
        File "/__w/CCF/CCF/build/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/__w/CCF/CCF/build/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/__w/CCF/CCF/build/env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 464, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 145, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 283, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line [27](https://github.com/microsoft/CCF/actions/runs/11239974653/job/31248339552#step:6:28)9, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-h1njbh[29](https://github.com/microsoft/CCF/actions/runs/11239974653/job/31248339552#step:6:30)/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 635, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/_integration/setuptools.py", line 123, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/_integration/setuptools.py", line 55, in _assign_version
          maybe_version = _get_version(config, force_write_version_files=True)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/_get_version_impl.py", line 101, in _get_version
          version_string = _format_version(parsed_version)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 445, in format_version
          main_version = _entrypoints._call_version_scheme(
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/_entrypoints.py", line 136, in _call_version_scheme
          result = scheme(version)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 241, in guess_next_dev_version
          return version.format_next_version(guess_next_version)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 189, in format_next_version
          guessed = guess_next(self, *k, **kw)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/version.py", line 2[34](https://github.com/microsoft/CCF/actions/runs/11239974653/job/31248339552#step:6:35), in guess_next_version
          return _modify_version._bump_dev(version) or _modify_version._bump_regex(version)
        File "/tmp/pip-build-env-h1njbh29/overlay/lib/python3.8/site-packages/setuptools_scm/_modify_version.py", line 27, in _bump_dev
          raise ValueError(
      ValueError: choosing custom numbers for the `.devX` distance is not supported.
       The 6.0.0.dev1 can't be bumped
      Please drop the tag or create a new supported one ending in .dev0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This started happening after the release of 6.0.0-dev1, and is apparently [caused by a conflicting use of the dev suffix](https://setuptools-scm.readthedocs.io/en/latest/usage/#default-versioning-scheme) by Python tooling (setuptools_scm specifically). It is unclear when this was introduced, we have done dozens of releases in the past, most recently 5.0.0-dev* without problems, most recently [5.0.0-dev18](https://pypi.org/project/ccf/5.0.0.dev18/) on June 13, 2024.

**Comment by achamayou** [comment]
Reverting `setuptools_scm` to the version we used at the time of 5.0.0-dev18 does not help #6543.

**Comment by achamayou** [comment]
Same with `setuptools` #6547. I am frustratingly unable to reproduce this issue anywhere outside the CI.

**Comment by achamayou** [comment]
What's failing is the install of the ccf package from the source directory:

```
+ pip install -q -U -e ../python/
  error: subprocess-exited-with-error
  ...
```

**Comment by achamayou** [comment]
After checking, we adopted pyproject.toml/setuptools_scm _after_ our last 5.0.0-dev release: https://github.com/microsoft/CCF/commits/c70e2be9560cca581d7fc4441b0bf95684ba92d8/python/pyproject.toml (July 22), so it looks possible and even likely that setuptools_scm _never_ supported "X.Y.X-devN" tags.
