### ISSUE TITLE
Memory leaks in PBFT

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#937]
In `end_to_end_logging_pbft`:

```
52: =================================================================
52: ==939==ERROR: LeakSanitizer: detected memory leaks
52: 
52: Direct leak of 1314 byte(s) in 3 object(s) allocated from:
52:     #0 0x4cd2ca in calloc (/mnt/build/1/s/build/cchost.virtual+0x4cd2ca)
52:     #1 0x7f1b9fcee200 in mbedtls_x509_crt_parse_der (liblogging.virtual.so+0x1edb200)
52:     #2 0x7f1b9fbea69a in messaging::BufferProcessor::run(ringbuffer::Reader&) /mnt/build/1/s/build/../src/ds/messaging.h:217:68
52: 
52: Direct leak of 1032 byte(s) in 3 object(s) allocated from:
52:     #0 0x4cd2ca in calloc (/mnt/build/1/s/build/cchost.virtual+0x4cd2ca)
52:     #1 0x7f1b9fd0a6e2 in eckey_alloc_wrap (liblogging.virtual.so+0x1ef76e2)
52: 
52: Indirect leak of 312 byte(s) in 9 object(s) allocated from:
52:     #0 0x4cd2ca in calloc (/mnt/build/1/s/build/cchost.virtual+0x4cd2ca)
52:     #1 0x7f1b9fcf2f02 in mbedtls_mpi_grow (liblogging.virtual.so+0x1edff02)
52: 
52: SUMMARY: AddressSanitizer: 2658 byte(s) leaked in 15 allocation(s).
```

https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=5835&view=logs&j=3d785448-79f8-5d6f-2822-33d5fb104445&t=653776bf-f979-5084-6a43-bdd05591254a&l=1396

**Comment by jumaffre** [comment]
Memory leak also observed in UDP with delay test: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=6019&view=logs&j=3d785448-79f8-5d6f-2822-33d5fb104445&t=653776bf-f979-5084-6a43-bdd05591254a&l=194

```
2: Direct leak of 104 byte(s) in 1 object(s) allocated from:
2:     #0 0x4fe2d2 in operator new(unsigned long) (/mnt/build/1/s/build/replica-test+0x4fe2d2)
2:     #1 0x76b497 in State::cow_single(int) /mnt/build/1/s/build/../src/consensus/pbft/libbyz/State.cpp:302:9
2:     #2 0x61600001cc87  (<unknown module>)
2: 
2: Direct leak of 40 byte(s) in 1 object(s) allocated from:
2:     #0 0x4fe2d2 in operator new(unsigned long) (/mnt/build/1/s/build/replica-test+0x4fe2d2)
2:     #1 0x76bdd5 in State::update_ptree(long) /mnt/build/1/s/build/../src/consensus/pbft/libbyz/State.cpp:443:16
2: 
2: SUMMARY: AddressSanitizer: 352 byte(s) leaked in 4 allocation(s).
2: 
2: Traceback (most recent call last):
2:   File "/mnt/build/1/s/tests/infra/libbyz/e2e_test.py", line 337, in <module>
2:     replica_nodes, f, args.with_delays, args.test_client_proxy, args.ledger
2:   File "/mnt/build/1/s/tests/infra/libbyz/e2e_test.py", line 201, in replica_checks
2:     log_errors(err_file)
2:   File "/mnt/build/1/s/tests/infra/libbyz/e2e_test.py", line 120, in log_errors
2:     assert errors == 0
2: AssertionError
 2/27 Test  #2: test_UDP_with_delay ..............***Failed  102.99 sec
```

**Comment by ashamis** [comment]
We have removed the UDP with delay test as it was using and leaking memory in un-used functionality  that is being deleted

**Comment by ashamis** [comment]
I did not mean to close this issue

**Comment by achamayou** [comment]
@ashamis I think it’s fine to consider the second issue as closed. The first has not been addressed but also not been reproduced.

I suggest we close this for now and open new separate issues if and when they turn up on the Daily build.
